## Creating a MultiIndex Series

In [95]:
import pandas as pd

df = pd.DataFrame({
    "Marks": [90, 80, 85, 88, 78, 86,88,76,56],
    "Name" :['Roman', 'Roman', 'Roman', 'Jackes', 'Jackes' ,'Jackes' ,'yash','yash','yash'],
    "Subject":['Maths', 'English','Science', 'Maths', 'English','Science','Maths','English','Science' ]
})
df

   Marks    Name  Subject
0     90   Roman    Maths
1     80   Roman  English
2     85   Roman  Science
3     88  Jackes    Maths
4     78  Jackes  English
5     86  Jackes  Science
6     88    yash    Maths
7     76    yash  English
8     56    yash  Science

In [96]:
df.index

RangeIndex(start=0, stop=9, step=1)

In [97]:
ndf=df.set_index(['Name','Subject'])
ndf

                Marks
Name   Subject
Roman  Maths       90
       English     80
       Science     85
Jackes Maths       88
       English     78
       Science     86
yash   Maths       88
       English     76
       Science     56

In [98]:
ndf.xs('Maths', level='Subject')
# xs=> cross section

        Marks
Name
Roman      90
Jackes     88
yash       88

## Here in ndf 2 levels of indexing : l1=Name l2=Subject

In [99]:
ndf.index

MultiIndex([( 'Roman',   'Maths'),
            ( 'Roman', 'English'),
            ( 'Roman', 'Science'),
            ('Jackes',   'Maths'),
            ('Jackes', 'English'),
            ('Jackes', 'Science'),
            (  'yash',   'Maths'),
            (  'yash', 'English'),
            (  'yash', 'Science')],
           names=['Name', 'Subject'])

In [100]:
ndf.loc['yash','Marks']

Subject
Maths      88
English    76
Science    56
Name: Marks, dtype: int64

In [101]:
print(ndf.iloc[0] )
print(ndf.iloc[2] )
print(ndf.iloc[3] )
print(ndf.iloc[-1] )

Marks    90
Name: (Roman, Maths), dtype: int64
Marks    85
Name: (Roman, Science), dtype: int64
Marks    88
Name: (Jackes, Maths), dtype: int64
Marks    56
Name: (yash, Science), dtype: int64

In [102]:
ndf.loc[['Roman','yash']]

               Marks
Name  Subject
Roman Maths       90
      English     80
      Science     85
yash  Maths       88
      English     76
      Science     56

In [103]:
# Convert inner index to columns.
ndf.unstack()

          Marks
Subject English Maths Science
Name
Jackes       78    88      86
Roman        80    90      85
yash         76    88      56

In [104]:

ndf.unstack().stack()

                Marks
Name   Subject
Jackes English     78
       Maths       88
       Science     86
Roman  English     80
       Maths       90
       Science     85
yash   English     76
       Maths       88
       Science     56

In [105]:
# Column have also hierarchical index:
import numpy as np
f1=pd.DataFrame(np.arange(12).reshape((4,3)),
                index=[['a','a','b','b'],[1,2,1,2]],
                columns=[['L1','L1','L2'],
                         ['C1','C2','C3']])
f1

    L1      L2
    C1  C2  C3
a 1  0   1   2
  2  3   4   5
b 1  6   7   8
  2  9  10  11

In [106]:
# use names instead of name
f1.index.names=['sr1','sr2']
f1.columns.names=['LEVEL','CLASS']
f1

LEVEL   L1      L2
CLASS   C1  C2  C3
sr1 sr2
a   1    0   1   2
    2    3   4   5
b   1    6   7   8
    2    9  10  11

In [107]:
f1.unstack()

LEVEL L1           L2
CLASS C1    C2     C3
sr2    1  2  1   2  1   2
sr1
a      0  3  1   4  2   5
b      6  9  7  10  8  11

In [108]:
f1.L1

CLASS    C1  C2
sr1 sr2
a   1     0   1
    2     3   4
b   1     6   7
    2     9  10

In [109]:
f1.L2

CLASS    C3
sr1 sr2
a   1     2
    2     5
b   1     8
    2    11

## Reordering and Sorting Levels

In [110]:
f1.swaplevel('sr1','sr2')

LEVEL   L1      L2
CLASS   C1  C2  C3
sr2 sr1
1   a    0   1   2
2   a    3   4   5
1   b    6   7   8
2   b    9  10  11

In [111]:
f1.sort_index(level='sr2')

LEVEL   L1      L2
CLASS   C1  C2  C3
sr1 sr2
a   1    0   1   2
b   1    6   7   8
a   2    3   4   5
b   2    9  10  11

In [112]:
f1.swaplevel(0, 1).sort_index(level=0)

LEVEL   L1      L2
CLASS   C1  C2  C3
sr2 sr1
1   a    0   1   2
    b    6   7   8
2   a    3   4   5
    b    9  10  11

##  Summary Statistics by Level

In [113]:
# In Pandas groupby is split–apply–combine operation.
# `groupby` gives you the power to categorize and aggregate data.

f1.groupby(level='sr2').sum()

LEVEL  L1      L2
CLASS  C1  C2  C3
sr2
1       6   8  10
2      12  14  16

In [114]:
f1.groupby(level='sr1').sum()

LEVEL  L1      L2
CLASS  C1  C2  C3
sr1
a       3   5   7
b      15  17  19

In [115]:
f1.groupby(level='sr1')['L1'].sum()

LEVEL  L1
CLASS  C1  C2
sr1
a       3   5
b      15  17

 ## Indexing with a DataFrame’s Columns
 `set_index()` and `reset_index()`

In [116]:
data = pd.DataFrame({
    'city': ['A', 'A', 'B', 'B'],
    'year': [2024, 2025, 2024, 2025],
    'sales': [100, 120, 90, 140],
    'profit': [20, 25, 18, 30]
})

data

  city  year  sales  profit
0    A  2024    100      20
1    A  2025    120      25
2    B  2024     90      18
3    B  2025    140      30

In [117]:
d2=data.set_index(['city','year'])
d2

           sales  profit
city year
A    2024    100      20
     2025    120      25
B    2024     90      18
     2025    140      30

In [118]:
data.set_index(['city', 'year'], drop=False)

          city  year  sales  profit
city year
A    2024    A  2024    100      20
     2025    A  2025    120      25
B    2024    B  2024     90      18
     2025    B  2025    140      30

In [119]:
d2.reset_index()

  city  year  sales  profit
0    A  2024    100      20
1    A  2025    120      25
2    B  2024     90      18
3    B  2025    140      30

## Combining and Merging Datasets:

In [120]:
df1=pd.DataFrame({'key':['b','b','a','c','a','a','b'],
                  'data1':range(7)})
df2=pd.DataFrame({"key":['a','b','d'],
                  'data2':range(3)})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

### The `join key` is the column whose `values are searched` in both DataFrames to determine `which rows should be combined`.

In [121]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

###  Summary
- `on=`                  → join on same column(s) in both DataFrames  
- `left_on` / `right_on` → join on different column names  
- `left_index` / `right_index` → join on indices  
- Nothing given → join on common column names

In [122]:
# merger function connect rows 
pd.merge(df1,df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [123]:
pd.merge(df1,df2,on='key')

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

- *By default `merge` does an `inner` join*
- *The keys in the result are the intersection*

In [124]:
df3=pd.DataFrame({'lkey':['b','b','a','c','a','a','b'],
                  'data1':range(7)})
df4=pd.DataFrame({"rkey":['a','b','d'],
                  'data2':range(3)})
pd.merge(df3,df4,left_on='lkey',right_on='rkey')

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

- *The `outer` join takes the union of the keys*

In [125]:
pd.merge(df1,df2,how='outer')

  key  data1  data2
0   a    2.0    0.0
1   a    4.0    0.0
2   a    5.0    0.0
3   b    0.0    1.0
4   b    1.0    1.0
5   b    6.0    1.0
6   c    3.0    NaN
7   d    NaN    2.0

In [126]:
dff1 = pd.DataFrame({'A': [1, 2]})
dff2 = pd.DataFrame({'B': ['x', 'y', 'z']})
pd.merge(dff1,dff2,how='cross')

   A  B
0  1  x
1  1  y
2  1  z
3  2  x
4  2  y
5  2  z

In [127]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                     'data1': range(6)})
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],
                     'data2': range(5)})

In [128]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [129]:
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [130]:
# Remember std: 11th's union set   df1 x df2 cartesian
pd.merge(df1,df2,on='key',how='left')

   key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [131]:
pd.merge(df1,df2,how='right',on='key')

   key  data1  data2
0    a    2.0      0
1    a    4.0      0
2    b    0.0      1
3    b    1.0      1
4    b    5.0      1
5    a    2.0      2
6    a    4.0      2
7    b    0.0      3
8    b    1.0      3
9    b    5.0      3
10   d    NaN      4

In [132]:
# cartesian product of the rows b : 3(left) x 2(right) times  
pd.merge(df1,df2,how='left')

   key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [133]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
     'key2': ['one', 'two', 'one'],
    'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                     'key2': ['one', 'one', 'one', 'two'],
                     'rval': [4, 5, 6, 7]})
pd.merge(left, right, on=['key1', 'key2'], how='outer')
# outer == union

  key1 key2  lval  rval
0  bar  one   3.0   6.0
1  bar  two   NaN   7.0
2  foo  one   1.0   4.0
3  foo  one   1.0   5.0
4  foo  two   2.0   NaN

In [134]:
pd.merge(left,right,on='key1')
# Match rows where key1 is equal.

# key2_x = from left
# key2_y = from right

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [135]:
pd.merge(left,right,on='key1',suffixes=('_left','_right'))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [136]:
pd.merge(left, right, on='key1', how='outer', indicator=True)

# Output adds:/

  key1 key2_x  lval key2_y  rval _merge
0  bar    one     3    one     6   both
1  bar    one     3    two     7   both
2  foo    one     1    one     4   both
3  foo    one     1    one     5   both
4  foo    two     2    one     4   both
5  foo    two     2    one     5   both

In [137]:
a = pd.DataFrame({'x':[1,2]})
b = pd.DataFrame({'x':[3,4]})

print(pd.concat([a,b]))
print(pd.concat([a,b],axis=1))

   x
0  1
1  2
0  3
1  4
   x  x
0  1  3
1  2  4

In [138]:
s1 = pd.Series([1, None, 3], index=['a','b','c'])
s2 = pd.Series([10, 20, 30], index=['a','b','c'])

s1.combine_first(s2)

a     1.0
b    20.0
c     3.0
dtype: float64

## Merging on Index

*if we pass `left_index=True` or `right_index=True` or `both` then index should be used as the merge key*

In [139]:
l1=pd.DataFrame({'key':['a','b','a','a','b','c'],
                 'value':range(6)})
r1=pd.DataFrame({'grp_val':[3.5,7]} ,index=['a','b'])
l1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [140]:
r1

   grp_val
a      3.5
b      7.0

In [141]:
pd.merge(l1,r1,how='outer',left_on='key',right_index=True)

# Reason: sort=True behavior in merge only for 'key'

  key  value  grp_val
0   a      0      3.5
2   a      2      3.5
3   a      3      3.5
1   b      1      7.0
4   b      4      7.0
5   c      5      NaN

## Merging on hierarchically indexed data

In [142]:
lefth=pd.DataFrame({'key1':['NY','NY','NY','TOKYO','TOKYO'],
                    'key2':[2000,2001,2002,2001,2002],
                    'data':np.arange(5.)})
righth = pd.DataFrame(np.arange(12).reshape((6, 2)),
                     index=[['TOKYO', 'TOKYO', 'NY', 'NY', 'NY', 'NY'],
                            [2001, 2000, 2000, 2000, 2001, 2002]],
                    columns=['event1', 'event2'])
lefth

    key1  key2  data
0     NY  2000   0.0
1     NY  2001   1.0
2     NY  2002   2.0
3  TOKYO  2001   3.0
4  TOKYO  2002   4.0

In [143]:
righth

            event1  event2
TOKYO 2001       0       1
      2000       2       3
NY    2000       4       5
      2000       6       7
      2001       8       9
      2002      10      11

In [144]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True,sort=True)

    key1  key2  data  event1  event2
0     NY  2000   0.0       4       5
0     NY  2000   0.0       6       7
1     NY  2001   1.0       8       9
2     NY  2002   2.0      10      11
3  TOKYO  2001   3.0       0       1

In [145]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True,how='outer')

    key1  key2  data  event1  event2
0     NY  2000   0.0     4.0     5.0
0     NY  2000   0.0     6.0     7.0
1     NY  2001   1.0     8.0     9.0
2     NY  2002   2.0    10.0    11.0
4  TOKYO  2000   NaN     2.0     3.0
3  TOKYO  2001   3.0     0.0     1.0
4  TOKYO  2002   4.0     NaN     NaN

In [146]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                    index=['a', 'c', 'e'],
                    columns=['Ohio', 'Nevada'])
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                    index=['b', 'c', 'd', 'e'],
                    columns=['Missouri', 'Alabama'])

In [147]:
pd.merge(left2,right2,left_index=True,right_index=True,how='outer')

   Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

###  Summary : `join()`
- `on=` → left DataFrame column(s) + right DataFrame index  
- `how=` → specify join type (`left`, `right`, `inner`, `outer`, `cross`)  
- `lsuffix` / `rsuffix` → handle overlapping column names  
- Nothing given → default join on indices  
- Unlike `merge()`, `join()` does **not** support `right_on`, `left_on`, `left_index`, or `right_index` parameters

In [148]:
left2.join(right2,how='outer')

   Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [149]:
l1.join(r1,on='key')

  key  value  grp_val
0   a      0      3.5
1   b      1      7.0
2   a      2      3.5
3   a      3      3.5
4   b      4      7.0
5   c      5      NaN

In [150]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                         index=['a', 'c', 'e', 'f'],
                         columns=['New York', 'Oregon'])
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [151]:
left2.join([right2,another])

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [152]:
left2.join([right2,another],how='outer')

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

## Concatenating Along an Axis

In [153]:
import numpy as np
arr=np.arange(24,36).reshape((3,4))
arr

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [154]:
np.concatenate([arr,arr],axis=1)

array([[24, 25, 26, 27, 24, 25, 26, 27],
       [28, 29, 30, 31, 28, 29, 30, 31],
       [32, 33, 34, 35, 32, 33, 34, 35]])

In [155]:
# index with no overlap
s1=pd.Series([0,1],index=['a','b'])
s2=pd.Series([2,3,4],index=['c','d','e'])
s3=pd.Series([5,6],index=['f','g'])

In [156]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [157]:
pd.concat([s1,s2,s3],axis=1)

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [158]:
s4=pd.concat([s1,s3])
s4

a    0
b    1
f    5
g    6
dtype: int64

In [159]:
pd.concat([s1,s4],axis=1)

     0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [160]:
pd.concat([s1,s4],axis=1,join='inner')

   0  1
a  0  0
b  1  1

*for desired indexes use `reindex` argument coz `join_axis` was deprecated*

In [161]:
pd.concat([s1,s4],axis=1).reindex(['a','c','b','e'])

     0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

In [162]:
pd.concat([s1,s4],axis=1,keys=['a','c'])

     a  c
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [163]:
result=pd.concat([s1,s1,s3],keys=['one','two','three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [164]:
result.unstack()

         a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [165]:
pd.concat([s1,s2,s3],axis=1,keys=['one','two','three'])

   one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [166]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                    columns=['three', 'four'])
df1

   one  two
a    0    1
b    2    3
c    4    5

In [167]:
df2

   three  four
a      5     6
c      7     8

In [168]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'])
# level 1 --> df1
# level 2 --> df2

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [169]:
pd.concat({'level1':df1 , 'level2' : df2},axis=1)

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [170]:
res2=pd.concat({'level1':df1 , 'level2' : df2},axis=1 , names=['upper','lower'])

In [171]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
df1

          a         b         c         d
0  0.912410 -0.830433  0.632584 -0.061335
1  0.257482  0.927028  0.208846  1.586688
2  1.109430 -0.193702 -0.027599  0.337936

In [172]:
df2

          b         d         a
0 -2.176986 -0.820872 -0.400405
1 -0.386336  1.332688 -0.013703

In [173]:
pd.concat([df1,df2],ignore_index=True)

          a         b         c         d
0  0.912410 -0.830433  0.632584 -0.061335
1  0.257482  0.927028  0.208846  1.586688
2  1.109430 -0.193702 -0.027599  0.337936
3 -0.400405 -2.176986       NaN -0.820872
4 -0.013703 -0.386336       NaN  1.332688