## Dropping is use for :<br>
- Removing unnecessary columns <br> 
- Removing duplicate rows 
- Data cleanning for ML
<br> 
we use drop function for it :  `obj.drop(label , axis = 0)` 
### Parameters:
* **labels** $\rightarrow$ Row/column name(s)
* **axis = 0** $\rightarrow$ Remove rows (default)
* **axis = 1** $\rightarrow$ Remove columns
* **inplace = True** $\rightarrow$ Modify original DataFrame
* **errors = 'ignore'** $\rightarrow$ Ignore error if label doesn't exist
*note: inplace=True change original

In [1]:
import numpy as np
import pandas as pd
data={
    "c1":["A","B","C","D","E","F","G","H","I"],
    "c2":[55,33,22,55,22,11,44,66,77],
    "c3":["n","o","n","n","n","o","n","o","o"]
}
df=pd.DataFrame(data)
df

  c1  c2 c3
0  A  55  n
1  B  33  o
2  C  22  n
3  D  55  n
4  E  22  n
5  F  11  o
6  G  44  n
7  H  66  o
8  I  77  o

In [2]:
# ndf=df.drop(5)
# ndf
ndf=df.drop("c1",axis=1,errors="ignore")
ndf

   c2 c3
0  55  n
1  33  o
2  22  n
3  55  n
4  22  n
5  11  o
6  44  n
7  66  o
8  77  o