### Syntax : for series -->  `obj[ <row_index> or <column label> ]`
### Syntax : for DataFrame -->

- `obj["column_label"] `     # Select column
- `obj[start:end] `          # Slice rows (Python slicing)

In [1]:
import pandas as pd

marks = pd.Series(
    [88, 76, 91, 67, 82, 95, 73, 84, 90, 79, 86, 92, 70, 81],
    index=[
        "Rahul", "Priya", "Amit", "Sneha", "Karan", "Neha", "Arjun",
        "Pooja", "Riya", "Vikas", "Anjali", "Yash", "Krishna", "Mehul"
    ],
    name="Marks"
)

print(marks)
print(marks.values)
print(marks["Amit"])
print(marks["Yash"])
print(marks[2:8])
print(marks.values[3:9])

Rahul      88
Priya      76
Amit       91
Sneha      67
Karan      82
Neha       95
Arjun      73
Pooja      84
Riya       90
Vikas      79
Anjali     86
Yash       92
Krishna    70
Mehul      81
Name: Marks, dtype: int64
[88 76 91 67 82 95 73 84 90 79 86 92 70 81]
91
92
Amit     91
Sneha    67
Karan    82
Neha     95
Arjun    73
Pooja    84
Name: Marks, dtype: int64
[67 82 95 73 84 90]

In [2]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "StudentID": [101,102,103,104,105,106,107,108,109,110,111,112,113,114],

    "Name": [
        "Rahul","Priya","Amit","Sneha","Karan","Neha","Arjun",
        "Pooja","Riya","Vikas","Anjali","Yash","Krishna","Mehul"
    ],

    "Branch": [
        "IT","CE","IT","ME","CE","IT","EC",
        "ME","IT","CE","EC","IT","ME","CE"
    ],

    "City": [
        "Surat","Ahmedabad","Rajkot","Vadodara","Surat","Bhavnagar","Jamnagar",
        "Surat","Rajkot","Ahmedabad","Vadodara","Surat","Bhavnagar","Rajkot"
    ],

    "Age": [19,20,18,21,20,19,22,21,18,20,19,18,22,21],

    "Semester": [3,4,3,5,4,3,6,5,3,4,6,3,5,4],

    "CGPA": [8.5,9.1,7.8,8.0,8.9,9.3,7.5,8.2,8.7,7.9,8.4,9.0,7.2,8.8],

    "Attendance": [92,95,80,88,90,97,75,84,91,82,89,96,78,87],

    "Internship": [
        "Yes","No","No","Yes","Yes","Yes","No",
        "No","Yes","No","Yes","Yes","No","Yes"
    ],

    "Placement": [
        "Yes","Yes","No","No","Yes","Yes","No",
        "No","Yes","No","Yes","Yes","No","Yes"
    ]
})

df

,StudentID,Name,Branch,City,Age,Semester,CGPA,Attendance,Internship,Placement
0,101,Rahul,IT,Surat,19,3,8.5,92,Yes,Yes
1,102,Priya,CE,Ahmedabad,20,4,9.1,95,No,Yes
2,103,Amit,IT,Rajkot,18,3,7.8,80,No,No
3,104,Sneha,ME,Vadodara,21,5,8.0,88,Yes,No
4,105,Karan,CE,Surat,20,4,8.9,90,Yes,Yes
5,106,Neha,IT,Bhavnagar,19,3,9.3,97,Yes,Yes
6,107,Arjun,EC,Jamnagar,22,6,7.5,75,No,No
7,108,Pooja,ME,Surat,21,5,8.2,84,No,No
8,109,Riya,IT,Rajkot,18,3,8.7,91,Yes,Yes
9,110,Vikas,CE,Ahmedabad,20,4,7.9,82,No,No
10,111,Anjali,EC,Vadodara,19,6,8.4,89,Yes,Yes
11,112,Yash,IT,Surat,18,3,9.0,96,Yes,Yes
12,113,Krishna,ME,Bhavnagar,22,5,7.2,78,No,No
13,114,Mehul,CE,Rajkot,21,4,8.8,87,Yes,Yes

In [3]:
print(df.iloc[11])
print(df.loc[11])
df[11:12]

StudentID       112
Name           Yash
Branch           IT
City          Surat
Age              18
Semester          3
CGPA            9.0
Attendance       96
Internship      Yes
Placement       Yes
Name: 11, dtype: object
StudentID       112
Name           Yash
Branch           IT
City          Surat
Age              18
Semester          3
CGPA            9.0
Attendance       96
Internship      Yes
Placement       Yes
Name: 11, dtype: object

,StudentID,Name,Branch,City,Age,Semester,CGPA,Attendance,Internship,Placement
11,112,Yash,IT,Surat,18,3,9.0,96,Yes,Yes

### Slicing 

- `.loc[row_labels, column_labels]`
- `.iloc[row_positions, column_positions]`

- `obj.loc[r1:r2 , c1:c2]`   # by labels
- `obj.iloc[r1:r2 , c1:c2] ` # by positions

- .loc (label-based) → slicing is inclusive of the end label.
👉 End label (r2 or c2) is included.


- .iloc (position-based) → behaves like normal Python slicing.
👉 End index (r2 or c2) is excluded.

In [4]:
print(df.loc[1,"Branch"])     # Label base indexing 
print(df.iloc[1,2])           # Position  base indexing 

# select one column
print("Student id:\n")

print(df["StudentID"])
print(df.loc[:,"City"])        # Coliumn label needed 
print(df.iloc[:,6] ,"\n")      # Column position needed

CE
CE
Student id:

0     101
1     102
2     103
3     104
4     105
5     106
6     107
7     108
8     109
9     110
10    111
11    112
12    113
13    114
Name: StudentID, dtype: int64
0         Surat
1     Ahmedabad
2        Rajkot
3      Vadodara
4         Surat
5     Bhavnagar
6      Jamnagar
7         Surat
8        Rajkot
9     Ahmedabad
10     Vadodara
11        Surat
12    Bhavnagar
13       Rajkot
Name: City, dtype: str
0     8.5
1     9.1
2     7.8
3     8.0
4     8.9
5     9.3
6     7.5
7     8.2
8     8.7
9     7.9
10    8.4
11    9.0
12    7.2
13    8.8
Name: CGPA, dtype: float64

In [5]:
# select one row :
print(df.loc[3])

print(df.iloc[3])

StudentID          104
Name             Sneha
Branch              ME
City          Vadodara
Age                 21
Semester             5
CGPA               8.0
Attendance          88
Internship         Yes
Placement           No
Name: 3, dtype: object
StudentID          104
Name             Sneha
Branch              ME
City          Vadodara
Age                 21
Semester             5
CGPA               8.0
Attendance          88
Internship         Yes
Placement           No
Name: 3, dtype: object

In [6]:
# slice one row
print(df.loc[5,"Name":"CGPA"])

Name             Neha
Branch             IT
City        Bhavnagar
Age                19
Semester            3
CGPA              9.3
Name: 5, dtype: object

In [7]:
# Slice column

print("Student id from 2 to 6:")
print(df.loc[2:6,"StudentID"]     , "\n")
print("Student Names from 3-8: ")
print(df.iloc[3:9,1])
# in iloc end is not included [x:end]

df.loc[:,"Name":"CGPA"]

Student id from 2 to 6:
2    103
3    104
4    105
5    106
6    107
Name: StudentID, dtype: int64

Student Names from 3-8:
3    Sneha
4    Karan
5     Neha
6    Arjun
7    Pooja
8     Riya
Name: Name, dtype: str

       Name Branch       City  Age  Semester  CGPA
0     Rahul     IT      Surat   19         3   8.5
1     Priya     CE  Ahmedabad   20         4   9.1
2      Amit     IT     Rajkot   18         3   7.8
3     Sneha     ME   Vadodara   21         5   8.0
4     Karan     CE      Surat   20         4   8.9
5      Neha     IT  Bhavnagar   19         3   9.3
6     Arjun     EC   Jamnagar   22         6   7.5
7     Pooja     ME      Surat   21         5   8.2
8      Riya     IT     Rajkot   18         3   8.7
9     Vikas     CE  Ahmedabad   20         4   7.9
10   Anjali     EC   Vadodara   19         6   8.4
11     Yash     IT      Surat   18         3   9.0
12  Krishna     ME  Bhavnagar   22         5   7.2
13    Mehul     CE     Rajkot   21         4   8.8

In [8]:
# Slice Sub DF 
df.loc[ 2: 7,"Name" : "Attendance" ]
# df.iloc[3:9,2:6]

    Name Branch       City  Age  Semester  CGPA  Attendance
2   Amit     IT     Rajkot   18         3   7.8          80
3  Sneha     ME   Vadodara   21         5   8.0          88
4  Karan     CE      Surat   20         4   8.9          90
5   Neha     IT  Bhavnagar   19         3   9.3          97
6  Arjun     EC   Jamnagar   22         6   7.5          75
7  Pooja     ME      Surat   21         5   8.2          84

### Boolean Indexing (or Boolean Selection).

In [9]:
# df.Age > 18 gives boolean output

df[df.Age > 18]  #   or  df[df["Age"] > 18] 

df[df["Placement"]=="Yes"]

,StudentID,Name,Branch,City,Age,Semester,CGPA,Attendance,Internship,Placement
0,101,Rahul,IT,Surat,19,3,8.5,92,Yes,Yes
1,102,Priya,CE,Ahmedabad,20,4,9.1,95,No,Yes
4,105,Karan,CE,Surat,20,4,8.9,90,Yes,Yes
5,106,Neha,IT,Bhavnagar,19,3,9.3,97,Yes,Yes
8,109,Riya,IT,Rajkot,18,3,8.7,91,Yes,Yes
10,111,Anjali,EC,Vadodara,19,6,8.4,89,Yes,Yes
11,112,Yash,IT,Surat,18,3,9.0,96,Yes,Yes
13,114,Mehul,CE,Rajkot,21,4,8.8,87,Yes,Yes

In [11]:
#  with multiple condition
df[(df.Branch =='CE')]
df[(df.CGPA >= 8) & (df.Internship =="Yes")]

,StudentID,Name,Branch,City,Age,Semester,CGPA,Attendance,Internship,Placement
0,101,Rahul,IT,Surat,19,3,8.5,92,Yes,Yes
3,104,Sneha,ME,Vadodara,21,5,8.0,88,Yes,No
4,105,Karan,CE,Surat,20,4,8.9,90,Yes,Yes
5,106,Neha,IT,Bhavnagar,19,3,9.3,97,Yes,Yes
8,109,Riya,IT,Rajkot,18,3,8.7,91,Yes,Yes
10,111,Anjali,EC,Vadodara,19,6,8.4,89,Yes,Yes
11,112,Yash,IT,Surat,18,3,9.0,96,Yes,Yes
13,114,Mehul,CE,Rajkot,21,4,8.8,87,Yes,Yes

In [ ]:
print(df["Age"] < 20)
print(df[df["Age"] < 20])

0      True
1     False
2      True
3     False
4     False
5      True
6     False
7     False
8      True
9     False
10     True
11     True
12    False
13    False
Name: Age, dtype: bool
    StudentID    Name Branch       City  Age  Semester  CGPA  Attendance  \
0         101   Rahul     IT      Surat   19         3   8.5          92
2         103    Amit     IT     Rajkot   18         3   7.8          80
5         106    Neha     IT  Bhavnagar   19         3   9.3          97
8         109    Riya     IT     Rajkot   18         3   8.7          91
10        111  Anjali     EC   Vadodara   19         6   8.4          89
11        112    Yash     IT      Surat   18         3   9.0          96

   Internship Placement
0         Yes       Yes
2          No        No
5         Yes       Yes
8         Yes       Yes
10        Yes       Yes
11        Yes       Yes

In [ ]:
print(df.loc[2,["CGPA","Branch","Age"]]     ,"\n")
print(df.iloc[2,[-1,5,6]]                   ,"\n")
print(df.loc[[5,6,7,8] , ["Age","StudentID"]],  "\n")
print(df.iloc[[2,5,3],[3,2,1]])

CGPA      7.8
Branch     IT
Age        18
Name: 2, dtype: object

Placement     No
Semester       3
CGPA         7.8
Name: 2, dtype: object

   Age  StudentID
5   19        106
6   22        107
7   21        108
8   18        109

        City Branch   Name
2     Rajkot     IT   Amit
5  Bhavnagar     IT   Neha
3   Vadodara     ME  Sneha

In [ ]:
df.loc[  : ,  : "City"]
df.iloc[  : ,  : 4]

    StudentID     Name Branch       City
0         101    Rahul     IT      Surat
1         102    Priya     CE  Ahmedabad
2         103     Amit     IT     Rajkot
3         104    Sneha     ME   Vadodara
4         105    Karan     CE      Surat
5         106     Neha     IT  Bhavnagar
6         107    Arjun     EC   Jamnagar
7         108    Pooja     ME      Surat
8         109     Riya     IT     Rajkot
9         110    Vikas     CE  Ahmedabad
10        111   Anjali     EC   Vadodara
11        112     Yash     IT      Surat
12        113  Krishna     ME  Bhavnagar
13        114    Mehul     CE     Rajkot

### `obj.at[ "row_label" , "column label" ]`
- "Label"+"Label" ==> one value 
- Returns one cell using label.

In [ ]:
print(df.at[6,"Name"])
print(df.at[3,"Attendance"])

Arjun
88

### `obj.iat[ <row_position> , <column_position> ]`
- "position"+"position" ==> one value 
- Returns one cell using position.

In [ ]:
print(df.iat[0,6])
print(df.iat[5,2])

8.5
IT

### `reindex()` 
- changes row , column or their order.
- Make copy unless assigned

In [ ]:
df.reindex([3,7,9,12],columns=["Name","Branch","Semester","CGPA"])

       Name Branch  Semester  CGPA
3     Sneha     ME         5   8.0
7     Pooja     ME         5   8.2
9     Vikas     CE         4   7.9
12  Krishna     ME         5   7.2