In [8]:
# Numpy unfuncs also operate with pandas objects 
import numpy as np  
import pandas as pd

fr=pd.DataFrame(np.random.randn(3,4),columns=list("pqrs"),index=list('abc'))
fr

          p         q         r         s
a  1.316195  1.013583  0.180182 -0.014722
b -1.219213 -0.380873  0.561441  0.409418
c  0.816492 -0.074783 -0.785296 -1.424807

In [9]:
fr=np.abs(fr)
fr

          p         q         r         s
a  1.316195  1.013583  0.180182  0.014722
b  1.219213  0.380873  0.561441  0.409418
c  0.816492  0.074783  0.785296  1.424807

In [10]:
f = lambda x : x*x
print(fr.apply(f))

          p         q         r         s
a  1.732368  1.027350  0.032466  0.000217
b  1.486482  0.145064  0.315216  0.167623
c  0.666659  0.005592  0.616691  2.030075

In [11]:
g = lambda x: x.max()-x.min()
print(fr.apply(g)       ,"\n\n")
print(fr.apply(g,axis="columns"))

p    0.499702
q    0.938800
r    0.605114
s    1.410085
dtype: float64


a    1.301473
b    0.838341
c    1.350024
dtype: float64


### The function passed to apply() need not return a `scalar value`;<br>it can also return `a Series with multiple values`.

In [12]:
def fun(x):
    return pd.Series([x.max(), x.min()],index=["max","min"])

fr.apply(fun)

            p         q         r         s
max  1.316195  1.013583  0.785296  1.424807
min  0.816492  0.074783  0.180182  0.014722

In [13]:
fmt  = lambda x : '%.2f' % x          # Return the 2 digit of each element 
fr.map(fmt)

      p     q     r     s
a  1.32  1.01  0.18  0.01
b  1.22  0.38  0.56  0.41
c  0.82  0.07  0.79  1.42

In [14]:
fr['r'].map(fmt)

a    0.18
b    0.56
c    0.79
Name: r, dtype: str