In [23]:
import numpy as np
import pandas as pd

obj=pd.Series(np.arange(5),index=list('dcabe'))
obj

d    0
c    1
a    2
b    3
e    4
dtype: int64

### `sort_index()` method return new sorted object.

In [24]:
obj2=obj.sort_index()
obj2

a    2
b    3
c    1
d    0
e    4
dtype: int64

In [25]:
obj2.sort_values(ascending=False)

e    4
b    3
a    2
c    1
d    0
dtype: int64

In [26]:
np.random.seed(42)    # for stop the random numbers 
df1=pd.DataFrame(np.random.randint(10,25,(6,7)) ,   index=list('pyzqrx') , columns=list('dcbaefg'))
df1

    d   c   b   a   e   f   g
p  16  13  22  24  20  17  22
y  14  16  19  12  16  20  20
z  17  14  13  17  17  12  15
q  14  11  17  21  23  15  11
r  21  14  10  21  19  15  22
x  21  18  10  20  20  24  19

In [27]:
df1.sort_index(axis=1)

    a   b   c   d   e   f   g
p  24  22  13  16  20  17  22
y  12  19  16  14  16  20  20
z  17  13  14  17  17  12  15
q  21  17  11  14  23  15  11
r  21  10  14  21  19  15  22
x  20  10  18  21  20  24  19

In [28]:
# using "by" argument we can sort any column it will be sorted  
print(df1.sort_values(by='d'))
print(df1.sort_values(by=["e","f","g"]))

    d   c   b   a   e   f   g
y  14  16  19  12  16  20  20
q  14  11  17  21  23  15  11
p  16  13  22  24  20  17  22
z  17  14  13  17  17  12  15
r  21  14  10  21  19  15  22
x  21  18  10  20  20  24  19
    d   c   b   a   e   f   g
y  14  16  19  12  16  20  20
z  17  14  13  17  17  12  15
r  21  14  10  21  19  15  22
p  16  13  22  24  20  17  22
x  21  18  10  20  20  24  19
q  14  11  17  21  23  15  11

In [29]:
#  Missing values are sorted to the end of the Series by default .
# even below the np.inf
ns=pd.Series([9,-3,np.inf,6,np.nan,5,-np.inf,10])
ns.sort_values()

6    -inf
1    -3.0
5     5.0
3     6.0
0     9.0
7    10.0
2     inf
4     NaN
dtype: float64

## Ranking in Pandas

- Ranking assigns a `position (rank) to each value.`

- Unlike sorting, ranking **does not rearrange the original data**.
  It only tells where each value would appear in sorted order.

Think of an example:

Sorting  → Arrange students by marks.

Ranking → Keep students in the same order but assign their ranks.

In [30]:
obj3=pd.Series([7,-6,5,4,2,-3,4])
obj3.rank()

0    7.0
1    1.0
2    6.0
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

##  Observe the Original Series

In [31]:
# Let's sort the Series to verify how rank() is calculated.

obj4=obj3.sort_values()
print(obj4)
print(obj4.rank())

1   -6
5   -3
4    2
3    4
6    4
2    5
0    7
dtype: int64
1    1.0
5    2.0
4    3.0
3    4.5
6    4.5
2    6.0
0    7.0
dtype: float64

## Since two values are equal (4 and 4),
   ## Pandas gives both the average rank.

<h3> Average = (4 + 5) / 2 = 4.5

- It first determines the position of every value
- in sorted order and then writes those ranks back
- to the original Series.

Sorting changes the order.

Ranking does not.

`sort_values()`   :  Actually rearranges the values.

`rank() `         :  Keeps the original order unchanged.

In [32]:
import pandas as pd

odf = pd.DataFrame({
    "Math":    [90, 80, 90, 70],
    "Science": [85, 95, 85, 75],
    "English": [88, 82, 91, 88]
})

odf

   Math  Science  English
0    90       85       88
1    80       95       82
2    90       85       91
3    70       75       88

In [33]:
odf.rank()

   Math  Science  English
0   3.5      2.5      2.5
1   2.0      4.0      1.0
2   3.5      2.5      4.0
3   1.0      1.0      2.5

In [34]:
ndf=odf.sort_values(by='Math')
print(ndf)

   Math  Science  English
3    70       75       88
1    80       95       82
0    90       85       88
2    90       85       91

# Ranking Methods

method="average" (default)

method="min"

method="max"

method="first"

method="dense"

In [35]:
# Method = "min"
# Every tied (same) value gets the smallest rank.


print(odf.rank())
odf.rank(method="min")

# that's why 3.5 and 3.5 becomes 3 and 3

   Math  Science  English
0   3.5      2.5      2.5
1   2.0      4.0      1.0
2   3.5      2.5      4.0
3   1.0      1.0      2.5

   Math  Science  English
0   3.0      2.0      2.0
1   2.0      4.0      1.0
2   3.0      2.0      4.0
3   1.0      1.0      2.0

In [36]:
# Method = "max"
# Every tied (same) value gets the largest rank.


print(odf.rank())
odf.rank(method="max")

# that's why 3.5 and 3.5 becomes 4 and 4

   Math  Science  English
0   3.5      2.5      2.5
1   2.0      4.0      1.0
2   3.5      2.5      4.0
3   1.0      1.0      2.5

   Math  Science  English
0   4.0      3.0      3.0
1   2.0      4.0      1.0
2   4.0      3.0      4.0
3   1.0      1.0      3.0

In [37]:
# Method = "first"
# If values are equal, assign ranks based on which one appears first in the original DataFrame.
print(odf)
odf.rank(method="first")

   Math  Science  English
0    90       85       88
1    80       95       82
2    90       85       91
3    70       75       88

   Math  Science  English
0   3.0      2.0      2.0
1   2.0      4.0      1.0
2   4.0      3.0      4.0
3   1.0      1.0      3.0

In [38]:
# Method = "dense"
# Give tied values the same rank without leaving gaps.
# Like "min", but don't skip numbers.

print(odf.rank(method="min"))
odf.rank(method="dense")

   Math  Science  English
0   3.0      2.0      2.0
1   2.0      4.0      1.0
2   3.0      2.0      4.0
3   1.0      1.0      2.0

   Math  Science  English
0   3.0      2.0      2.0
1   2.0      3.0      1.0
2   3.0      2.0      3.0
3   1.0      1.0      2.0

### Axis Indexes with Duplicate Labels

In [39]:
obj5=pd.Series(range(5),index=list('aabcd'))
obj5

a    0
a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
# is_unique property tells us whether its labels are unique or not 
print(obj5.is_unique)
print(obj5.index.is_unique)

True
False

In [41]:
# If we enter duplicate index then it gives all the rows with duplicates

print(obj5['c'])
print(obj5['a'])

# This can make our code more complicated

3
a    0
a    1
dtype: int64

In [42]:
d1=pd.DataFrame(np.random.randn(4,3),index=list('abbc'))
d1

          0         1         2
a -0.251044 -0.163867 -1.476330
b  1.486981 -0.024455  0.355551
b  0.417011  0.832462 -0.293399
c -0.029839  0.095126  0.664654

In [43]:
d1.loc['b']

          0         1         2
b  1.486981 -0.024455  0.355551
b  0.417011  0.832462 -0.293399