In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Raj", "Amit", "Neha", "Riya", "Karan", "Priya", "Rahul", "Sneha"],
    "Age": [20, 21, 22, 23, 24, 20, 25, 22],
    "City": ["Surat", "Rajkot", "Ahmedabad", "Vadodara", "Surat", "Rajkot", "Bhavnagar", "Ahmedabad"],
    "Marks": [88, 76, 91, 67, 82, 95, 73, 89],
    "Branch": ["IT", "CE", "IT", "ME", "CE", "IT", "EC", "ME"]
})

df

    Name  Age       City  Marks Branch
0    Raj   20      Surat     88     IT
1   Amit   21     Rajkot     76     CE
2   Neha   22  Ahmedabad     91     IT
3   Riya   23   Vadodara     67     ME
4  Karan   24      Surat     82     CE
5  Priya   20     Rajkot     95     IT
6  Rahul   25  Bhavnagar     73     EC
7  Sneha   22  Ahmedabad     89     ME

In [ ]:
print(df.reindex([1,2,3,0,4,5,7,6]))
df # df's index are immutable

    Name  Age       City  Marks Branch
1   Amit   21     Rajkot     76     CE
2   Neha   22  Ahmedabad     91     IT
3   Riya   23   Vadodara     67     ME
0    Raj   20      Surat     88     IT
4  Karan   24      Surat     82     CE
5  Priya   20     Rajkot     95     IT
7  Sneha   22  Ahmedabad     89     ME
6  Rahul   25  Bhavnagar     73     EC

    Name  Age       City  Marks Branch
0    Raj   20      Surat     88     IT
1   Amit   21     Rajkot     76     CE
2   Neha   22  Ahmedabad     91     IT
3   Riya   23   Vadodara     67     ME
4  Karan   24      Surat     82     CE
5  Priya   20     Rajkot     95     IT
6  Rahul   25  Bhavnagar     73     EC
7  Sneha   22  Ahmedabad     89     ME