In [2]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "Name": ["Raj", "Amit", "Neha", "Riya", "Karan", "Priya", "Rahul", "Sneha"],
    "Age": [20, 21, 22, 23, 24, 20, 25, 22],
    "City": ["Surat", "Rajkot", "Ahmedabad", "Vadodara", "Surat", "Rajkot", "Bhavnagar", "Ahmedabad"],
    "Marks": [88, 76, 91, 67, 82, 95, 73, 89],
    "Branch": ["IT", "CE", "IT", "ME", "CE", "IT", "EC", "ME"]
})

df

    Name  Age       City  Marks Branch
0    Raj   20      Surat     88     IT
1   Amit   21     Rajkot     76     CE
2   Neha   22  Ahmedabad     91     IT
3   Riya   23   Vadodara     67     ME
4  Karan   24      Surat     82     CE
5  Priya   20     Rajkot     95     IT
6  Rahul   25  Bhavnagar     73     EC
7  Sneha   22  Ahmedabad     89     ME

### If we specify a sequence of columns , the DF columns will be arranged in that order. it's because of the **DataFrame's internal indexing and selection mechanism**, not because DataFrames are mutable.

In [3]:
df=pd.DataFrame(df,columns=['Name','Branch','City','Marks','Age'])
df

    Name Branch       City  Marks  Age
0    Raj     IT      Surat     88   20
1   Amit     CE     Rajkot     76   21
2   Neha     IT  Ahmedabad     91   22
3   Riya     ME   Vadodara     67   23
4  Karan     CE      Surat     82   24
5  Priya     IT     Rajkot     95   20
6  Rahul     EC  Bhavnagar     73   25
7  Sneha     ME  Ahmedabad     89   22

### If we pass a column that isn't contained in <br>the dict, it will appear with missing values `(NaN)`  in the result.

In [4]:
df2=pd.DataFrame(df,columns=['Name','Branch','City','Marks','Age','debt'])
df2

    Name Branch       City  Marks  Age  debt
0    Raj     IT      Surat     88   20   NaN
1   Amit     CE     Rajkot     76   21   NaN
2   Neha     IT  Ahmedabad     91   22   NaN
3   Riya     ME   Vadodara     67   23   NaN
4  Karan     CE      Surat     82   24   NaN
5  Priya     IT     Rajkot     95   20   NaN
6  Rahul     EC  Bhavnagar     73   25   NaN
7  Sneha     ME  Ahmedabad     89   22   NaN

### A Column in DF can be retrieved as a Series either by dict-like `notation` or by `attribute`:

In [5]:
df["Name"]
# df.Name

# df['City']
df.City

0        Surat
1       Rajkot
2    Ahmedabad
3     Vadodara
4        Surat
5       Rajkot
6    Bhavnagar
7    Ahmedabad
Name: City, dtype: str

###  Rows/Columns can be retrieved either by <br>label using `.loc` or by<br>integer position using    `.iloc.`
- .loc[x:y] → `End is INCLUDED`
-  .iloc[x:y] → `End is EXCLUDED (like normal Python slicing) `

In [6]:
#  label base indexing  :  
#  df.loc[<row_label> , "column_label"]  --> for single element 
#  If 2nd argument was not given then loc and iloc both give whole row other wise single element 

print(df.loc[2]  ,   "\n")
print(df.loc[2,"City"]  ,"\n")

# Position base indexing : 
# df.iloc[<row_label> , <column_number>] 
print(df.iloc[2]  ,   "\n")  


print(df.iloc[2,1])

Name           Neha
Branch           IT
City      Ahmedabad
Marks            91
Age              22
Name: 2, dtype: object

Ahmedabad

Name           Neha
Branch           IT
City      Ahmedabad
Marks            91
Age              22
Name: 2, dtype: object

IT

In [7]:
# Columns can be modified by assignment 
df['debt']=56
# df['debt']=np.arange(8)
df

    Name Branch       City  Marks  Age  debt
0    Raj     IT      Surat     88   20    56
1   Amit     CE     Rajkot     76   21    56
2   Neha     IT  Ahmedabad     91   22    56
3   Riya     ME   Vadodara     67   23    56
4  Karan     CE      Surat     82   24    56
5  Priya     IT     Rajkot     95   20    56
6  Rahul     EC  Bhavnagar     73   25    56
7  Sneha     ME  Ahmedabad     89   22    56

In [8]:
val=pd.Series([4,-6,8,9],index=[1,3,5,6])
df['debt']=val
df

    Name Branch       City  Marks  Age  debt
0    Raj     IT      Surat     88   20   NaN
1   Amit     CE     Rajkot     76   21   4.0
2   Neha     IT  Ahmedabad     91   22   NaN
3   Riya     ME   Vadodara     67   23  -6.0
4  Karan     CE      Surat     82   24   NaN
5  Priya     IT     Rajkot     95   20   8.0
6  Rahul     EC  Bhavnagar     73   25   9.0
7  Sneha     ME  Ahmedabad     89   22   NaN

In [9]:
#  Added new column with boolean values where City is Ahemedabad

df["new_col"]=df.City == "Ahmedabad"
df

    Name Branch       City  Marks  Age  debt  new_col
0    Raj     IT      Surat     88   20   NaN    False
1   Amit     CE     Rajkot     76   21   4.0    False
2   Neha     IT  Ahmedabad     91   22   NaN     True
3   Riya     ME   Vadodara     67   23  -6.0    False
4  Karan     CE      Surat     82   24   NaN    False
5  Priya     IT     Rajkot     95   20   8.0    False
6  Rahul     EC  Bhavnagar     73   25   9.0    False
7  Sneha     ME  Ahmedabad     89   22   NaN     True

In [10]:
# using del key word we can delete
del df["new_col"]    # 'new_col'  column gone permanently.
print(df.columns)
df

Index(['Name', 'Branch', 'City', 'Marks', 'Age', 'debt'], dtype='str')

    Name Branch       City  Marks  Age  debt
0    Raj     IT      Surat     88   20   NaN
1   Amit     CE     Rajkot     76   21   4.0
2   Neha     IT  Ahmedabad     91   22   NaN
3   Riya     ME   Vadodara     67   23  -6.0
4  Karan     CE      Surat     82   24   NaN
5  Priya     IT     Rajkot     95   20   8.0
6  Rahul     EC  Bhavnagar     73   25   9.0
7  Sneha     ME  Ahmedabad     89   22   NaN

In [11]:
#  using drop function we can delete whole row form DF
df_copy=df.drop(2)   
print(df_copy.index)
df

Index([0, 1, 3, 4, 5, 6, 7], dtype='int64')

    Name Branch       City  Marks  Age  debt
0    Raj     IT      Surat     88   20   NaN
1   Amit     CE     Rajkot     76   21   4.0
2   Neha     IT  Ahmedabad     91   22   NaN
3   Riya     ME   Vadodara     67   23  -6.0
4  Karan     CE      Surat     82   24   NaN
5  Priya     IT     Rajkot     95   20   8.0
6  Rahul     EC  Bhavnagar     73   25   9.0
7  Sneha     ME  Ahmedabad     89   22   NaN

### Case 1: Nested dicts with `same keys`

In [12]:
data = {
    "Student1": {"Name": "Alex", "Age": 21, "City": "Delhi"},
    "Student2": {"Name": "Bob", "Age": 22, "City": "Mumbai"},
    "Student3": {"Name": "Cathy", "Age": 23, "City": "Pune"}
}

df3 = pd.DataFrame(data)
df3

     Student1 Student2 Student3
Name     Alex      Bob    Cathy
Age        21       22       23
City    Delhi   Mumbai     Pune

### Case 2: Nested dicts with `different keys`

In [13]:
data = {
    "Student1": {"Name": "Alex", "Age": 21},
    "Student2": {"Name": "Bob", "Marks": 85},
    "Student3": {"City": "Pune", "Age": 23}
}

df4 = pd.DataFrame(data).T
df4

          Name  Age Marks  City
Student1  Alex   21   NaN   NaN
Student2   Bob  NaN    85   NaN
Student3   NaN   23   NaN  Pune

### Case 3: Deep nesting `(dict inside dict inside dict)`

In [14]:
data = {
    "Student1": {"Info": {"Name": "Alex", "Age": 21}, "Marks": {"Math": 85, "Sci": 90}},
    "Student2": {"Info": {"Name": "Bob", "Age": 22}, "Marks": {"Math": 80, "Sci": 88}}
}

df = pd.json_normalize(data)
df

,Student1.Info.Name,Student1.Info.Age,Student1.Marks.Math,Student1.Marks.Sci,Student2.Info.Name,Student2.Info.Age,Student2.Marks.Math,Student2.Marks.Sci
0,Alex,21,85,90,Bob,22,80,88

In [ ]:


data = {
    "Name": ["Aman","Riya","Kunal","Neha","Sahil","Priya"],
    "Age": [17,19,18,22,18,20],
    "Marks": [75,85,92,60,80,92],
    "City": ["Ahmedabad","Surat","Rajkot","Surat","Baroda","Ahmedabad"]
}
df5 = pd.DataFrame(data)
df5

    Name  Age  Marks       City
0   Aman   17     75  Ahmedabad
1   Riya   19     85      Surat
2  Kunal   18     92     Rajkot
3   Neha   22     60      Surat
4  Sahil   18     80     Baroda
5  Priya   20     92  Ahmedabad

In [ ]:
# 1.)  Boolean Indexing  (masking)
df5[df5.Age > 18]
df5[df5["Age"] > 18]
df5[df5.Marks > 90]

# With multiple condition : 
df5[(df5.Age == 18) & (df5.Marks > 90)]
df5[(df5["Age"] > 18) | (df5["Marks"] > 90)]         
df5[~(df5["Marks"] > 90)]

[0    False
 1     True
 2    False
 3     True
 4    False
 5     True
 Name: Age, dtype: bool]

In [35]:
# 2)  isin() function 
df5[df5["City"].isin(["Ahmedabad","Surat"])]

    Name  Age  Marks       City
0   Aman   17     75  Ahmedabad
1   Riya   19     85      Surat
3   Neha   22     60      Surat
5  Priya   20     92  Ahmedabad

In [ ]:
# 3) query() 
#  internally converts to df[df["Marks"]>80] : 
df5.query("Marks > 80")

df5.query("Age == 18 and Marks > 80")
df5.query("Age == 18 or Marks > 80")
df5.query("Age == 18 and not Marks > 80")
df5.query("not (Marks > 80)")   
df5.query("not (Age == 18 and Marks > 80)")

    Name  Age  Marks       City
0   Aman   17     75  Ahmedabad
3   Neha   22     60      Surat
4  Sahil   18     80     Baroda

In [ ]:
# 4) sort_values()
df5.sort_values("Age")
df5.sort_values("Age",ascending=False)
# note: By defalut ascending is "True" .

    Name  Age  Marks       City
3   Neha   22     60      Surat
5  Priya   20     92  Ahmedabad
1   Riya   19     85      Surat
2  Kunal   18     92     Rajkot
4  Sahil   18     80     Baroda
0   Aman   17     75  Ahmedabad

In [ ]:
df5.sort_values(["City","Marks"])
#  First sort City wise then sort Marks wise between same City 
df5.sort_values(["Marks","Age"])

    Name  Age  Marks       City
3   Neha   22     60      Surat
5  Priya   20     92  Ahmedabad
1   Riya   19     85      Surat
2  Kunal   18     92     Rajkot
4  Sahil   18     80     Baroda
0   Aman   17     75  Ahmedabad

In [ ]:
#  sort_index()
df5.sort_index()
# if df was previously sorted/shuffled, this puts rows back by index number.

    Name  Age  Marks       City
0   Aman   17     75  Ahmedabad
1   Riya   19     85      Surat
2  Kunal   18     92     Rajkot
3   Neha   22     60      Surat
4  Sahil   18     80     Baroda
5  Priya   20     92  Ahmedabad