Raw Data
   │
   ▼
Data Collection
   │
   ▼
Data Cleaning
   │
   ├── Handle Missing Values
   ├── Remove Duplicates
   ├── Fix Data Types
   ├── Handle Outliers
   ├── Clean Text
   └── Correct Invalid Values
   │
   ▼
Data Preparation / Preprocessing
   │
   ├── Feature Engineering
   ├── Feature Selection
   ├── Encoding
   ├── Scaling
   ├── Transformation
   ├── Combining Datasets
   └── Train-Test Split
   │
   ▼
Exploratory Data Analysis (EDA) / Visualization
   │
   ▼
Machine Learning Model

# HANDLING MISSING VALUES

In [2]:
import pandas as pd
from numpy import nan as NA

sd=pd.Series(["surat","bardoli","GN",NA,"A'bad",])
sd.isnull()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [3]:
sd[1]=None

print(sd.isnull())
print("total nulls :",sd.isnull().sum())

0    False
1     True
2    False
3     True
4    False
dtype: bool
total nulls : 2

In [4]:
print(sd.dropna())
print(sd[sd.notnull()])

0    surat
2       GN
4    A'bad
dtype: str
0    surat
2       GN
4    A'bad
dtype: str

In [5]:
df = pd.DataFrame({
    "Name": ["Raj", "Amit", "Nolan", "Roger", "Karan", NA],
    "Age": [20, NA, 22, 21, NA, 24],
    "City": ["Surat", "Delhi", NA, "Mumbai", "Pune", "Ahmedabad"],
    "Salary": [50000, 45000, NA, 52000, 47000, NA]
})

df

    Name   Age       City   Salary
0    Raj  20.0      Surat  50000.0
1   Amit   NaN      Delhi  45000.0
2  Nolan  22.0        NaN      NaN
3  Roger  21.0     Mumbai  52000.0
4  Karan   NaN       Pune  47000.0
5    NaN  24.0  Ahmedabad      NaN

In [6]:
df.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False   True  False   False
2  False  False   True    True
3  False  False  False   False
4  False   True  False   False
5   True  False  False    True

In [7]:
df.isnull().sum()

Name      1
Age       2
City      1
Salary    2
dtype: int64

In [8]:
df.dropna()
# Remove the entire row if included minimun one nan

    Name   Age    City   Salary
0    Raj  20.0   Surat  50000.0
3  Roger  21.0  Mumbai  52000.0

In [9]:
df.dropna(how="all")
# drop row which contain all NA .

    Name   Age       City   Salary
0    Raj  20.0      Surat  50000.0
1   Amit   NaN      Delhi  45000.0
2  Nolan  22.0        NaN      NaN
3  Roger  21.0     Mumbai  52000.0
4  Karan   NaN       Pune  47000.0
5    NaN  24.0  Ahmedabad      NaN

In [10]:
df2=pd.DataFrame([[2,3,4],[NA,NA,NA],[NA,5,NA],[2,4,NA]])
df2
df2.dropna()
# here row was dropped

     0    1    2
0  2.0  3.0  4.0

In [11]:
df2[3]=NA
print(df2)
df2.dropna(axis=1,how='all')

     0    1    2   3
0  2.0  3.0  4.0 NaN
1  NaN  NaN  NaN NaN
2  NaN  5.0  NaN NaN
3  2.0  4.0  NaN NaN

     0    1    2
0  2.0  3.0  4.0
1  NaN  NaN  NaN
2  NaN  5.0  NaN
3  2.0  4.0  NaN

In [12]:
import numpy as np
df3=pd.DataFrame(np.random.randn(7,3))
df3

          0         1         2
0  0.751784 -0.538508  0.011486
1  0.475923  0.364233  1.477952
2 -1.975793  1.294299  1.109200
3  0.464104 -1.702292 -0.843566
4 -0.693414  1.392627  0.201708
5  0.267509  3.520310  1.045516
6  0.940349  0.382582 -0.367955

In [13]:
df3.iloc[:4,1]=NA
df3.iloc[:2,2]=NA
df3

          0         1         2
0  0.751784       NaN       NaN
1  0.475923       NaN       NaN
2 -1.975793       NaN  1.109200
3  0.464104       NaN -0.843566
4 -0.693414  1.392627  0.201708
5  0.267509  3.520310  1.045516
6  0.940349  0.382582 -0.367955

In [14]:
# Keep a row (or column) only if it has at least thresh non-missing (non-NaN) values.
df3.dropna(thresh=2)

          0         1         2
2 -1.975793       NaN  1.109200
3  0.464104       NaN -0.843566
4 -0.693414  1.392627  0.201708
5  0.267509  3.520310  1.045516
6  0.940349  0.382582 -0.367955

In [15]:
# fill mssing value with 0.
df3.fillna(0)

          0         1         2
0  0.751784  0.000000  0.000000
1  0.475923  0.000000  0.000000
2 -1.975793  0.000000  1.109200
3  0.464104  0.000000 -0.843566
4 -0.693414  1.392627  0.201708
5  0.267509  3.520310  1.045516
6  0.940349  0.382582 -0.367955

In [16]:
# fill different value in columns 
df3.fillna({1:2,2:0})

          0         1         2
0  0.751784  2.000000  0.000000
1  0.475923  2.000000  0.000000
2 -1.975793  2.000000  1.109200
3  0.464104  2.000000 -0.843566
4 -0.693414  1.392627  0.201708
5  0.267509  3.520310  1.045516
6  0.940349  0.382582 -0.367955

In [17]:
df4=pd.DataFrame(np.random.randn(6,3))
df4.iloc[2:,1]=NA
df4.iloc[4:,2]=NA
df4

          0         1         2
0 -0.093452 -1.121273  0.787512
1  0.587910  0.329173 -0.650541
2  1.479109       NaN -0.606352
3 -2.045096       NaN -2.079006
4 -0.304275       NaN       NaN
5  0.524810       NaN       NaN

### Old way (Pandas < 3.0)
- `df.fillna(method="ffill")`
- `df.fillna(method="bfill")`

### New way (Pandas 3.0+)
- `df.ffill()`
- `df.bfill()`

In [18]:
# forward fill 
df4.ffill()

          0         1         2
0 -0.093452 -1.121273  0.787512
1  0.587910  0.329173 -0.650541
2  1.479109  0.329173 -0.606352
3 -2.045096  0.329173 -2.079006
4 -0.304275  0.329173 -2.079006
5  0.524810  0.329173 -2.079006

In [19]:
# forward fill with limit.
df4.ffill(limit=2)

          0         1         2
0 -0.093452 -1.121273  0.787512
1  0.587910  0.329173 -0.650541
2  1.479109  0.329173 -0.606352
3 -2.045096  0.329173 -2.079006
4 -0.304275       NaN -2.079006
5  0.524810       NaN -2.079006

In [20]:

s2=pd.Series([1,NA,3.5,NA,7])
s2.fillna(s2.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [21]:
xdf=pd.DataFrame(np.random.randint(11,44,(4,3)))
xdf
xdf.iloc[1,1]=NA
xdf.iloc[3,1]=NA
xdf.iloc[1,2]=NA
xdf

    0     1     2
0  38  23.0  12.0
1  37   NaN   NaN
2  29  32.0  39.0
3  28   NaN  28.0

In [22]:
xdf.isnull()

       0      1      2
0  False  False  False
1  False   True   True
2  False  False  False
3  False   True  False

In [23]:
xdf.loc[0,0]=None
xdf.isnull()

       0      1      2
0   True  False  False
1  False   True   True
2  False  False  False
3  False   True  False

In [24]:
xdf.dropna(thresh=2)

      0     1     2
0   NaN  23.0  12.0
2  29.0  32.0  39.0
3  28.0   NaN  28.0

 #  DATA TRANSFORMATION :

## 1) Removing Duplicates :

In [25]:
import pandas as pd

df = pd.DataFrame({
    "Name":   ["Raj", "Amit", "Raj", "Nolan", "Amit"],
    "Age":    [20, 21, 20, 22, 23],
    "City":   ["Ahmedabad", "Surat", "Ahmedabad", "Rajkot", "Surat"],
    "Course": ["IT", "CE", "IT", "ME", "CE"],
    "Marks":  [85, 90, 85, 88, 95]
})

df

    Name  Age       City Course  Marks
0    Raj   20  Ahmedabad     IT     85
1   Amit   21      Surat     CE     90
2    Raj   20  Ahmedabad     IT     85
3  Nolan   22     Rajkot     ME     88
4   Amit   23      Surat     CE     95

In [26]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [27]:
df.drop_duplicates()

    Name  Age       City Course  Marks
0    Raj   20  Ahmedabad     IT     85
1   Amit   21      Surat     CE     90
3  Nolan   22     Rajkot     ME     88
4   Amit   23      Surat     CE     95

In [28]:
df

    Name  Age       City Course  Marks
0    Raj   20  Ahmedabad     IT     85
1   Amit   21      Surat     CE     90
2    Raj   20  Ahmedabad     IT     85
3  Nolan   22     Rajkot     ME     88
4   Amit   23      Surat     CE     95

In [29]:
df.drop_duplicates("Name")

    Name  Age       City Course  Marks
0    Raj   20  Ahmedabad     IT     85
1   Amit   21      Surat     CE     90
3  Nolan   22     Rajkot     ME     88

In [30]:
df.drop_duplicates("Course")

    Name  Age       City Course  Marks
0    Raj   20  Ahmedabad     IT     85
1   Amit   21      Surat     CE     90
3  Nolan   22     Rajkot     ME     88

### keep arguement

In [31]:
df = pd.DataFrame({
    "Name": ["Raj", "Amit", "Raj", "Neha", "Raj"],
    "Age":  [20, 21, 20, 22, 20],
    "c3" :['a','a','b','c','d']
})

df

   Name  Age c3
0   Raj   20  a
1  Amit   21  a
2   Raj   20  b
3  Neha   22  c
4   Raj   20  d

In [32]:
df.drop_duplicates()

   Name  Age c3
0   Raj   20  a
1  Amit   21  a
2   Raj   20  b
3  Neha   22  c
4   Raj   20  d

In [33]:
# if duplicates were present then it only keep the last one 
df.drop_duplicates(['c3'], keep='last')

   Name  Age c3
1  Amit   21  a
2   Raj   20  b
3  Neha   22  c
4   Raj   20  d

In [34]:
# False remove the all duplicates 
df.drop_duplicates('c3', keep=False)

   Name  Age c3
2   Raj   20  b
3  Neha   22  c
4   Raj   20  d

In [35]:
df.drop_duplicates(['Name','Age'],keep='last')

   Name  Age c3
1  Amit   21  a
3  Neha   22  c
4   Raj   20  d

## TRANSFORMING DATA USING FUNCTION OR MAPPING

In [36]:
data=pd.DataFrame({'Players':['VK','KW','MSD','ABD','MG','JR','FD'],
                   'cars':[5,3,7,2,8,2,6]
                   })
data

  Players  cars
0      VK     5
1      KW     3
2     MSD     7
3     ABD     2
4      MG     8
5      JR     2
6      FD     6

In [37]:
player_to_nation={
    "vk":'ind',
    "msd":'ind',
    'jr':'eng',
    'abd':'rsa',
    'kw':'nz',
    'fd':'rsa',
    'mg':'nz'
}

In [38]:
l_c=data['Players'].str.lower()
l_c

0     vk
1     kw
2    msd
3    abd
4     mg
5     jr
6     fd
Name: Players, dtype: str

In [39]:
data['nation']=l_c.map(player_to_nation)
data

  Players  cars nation
0      VK     5    ind
1      KW     3     nz
2     MSD     7    ind
3     ABD     2    rsa
4      MG     8     nz
5      JR     2    eng
6      FD     6    rsa

In [40]:
data['Players'].map(lambda x:player_to_nation[x.lower()])
# data

0    ind
1     nz
2    ind
3    rsa
4     nz
5    eng
6    rsa
Name: Players, dtype: str

## Replacing Values

In [41]:
ns=pd.Series([1,-999,5,-1000,3,-999,2,4,-999])
ns

0       1
1    -999
2       5
3   -1000
4       3
5    -999
6       2
7       4
8    -999
dtype: int64

In [42]:
ns.replace(-999,NA)
ns

0       1
1    -999
2       5
3   -1000
4       3
5    -999
6       2
7       4
8    -999
dtype: int64

In [43]:
ns.replace([-999,-1000],[0,1])

0    1
1    0
2    5
3    1
4    3
5    0
6    2
7    4
8    0
dtype: int64

In [44]:
ns.replace({5:10,-1000:NA})

0      1.0
1   -999.0
2     10.0
3      NaN
4      3.0
5   -999.0
6      2.0
7      4.0
8   -999.0
dtype: float64

## Renaming Axis Indexes

In [45]:
new_df=pd.DataFrame(np.random.randint(5,10,(5,4)),
                    index=['rajkot','gn','surat','bardoli','navsari'],
                    columns=['one','two','three','four'])
new_df

         one  two  three  four
rajkot     9    8      9     7
gn         9    6      8     8
surat      7    7      8     5
bardoli    7    7      5     6
navsari    7    7      9     8

In [46]:
tf=lambda x:x.upper()
new_df.index.map(tf)

Index(['RAJKOT', 'GN', 'SURAT', 'BARDOLI', 'NAVSARI'], dtype='str')

In [47]:
new_df.index=new_df.index.map(tf)
new_df

         one  two  three  four
RAJKOT     9    8      9     7
GN         9    6      8     8
SURAT      7    7      8     5
BARDOLI    7    7      5     6
NAVSARI    7    7      9     8

In [48]:
new_df.rename(index=str.title,columns=str.upper)

         ONE  TWO  THREE  FOUR
Rajkot     9    8      9     7
Gn         9    6      8     8
Surat      7    7      8     5
Bardoli    7    7      5     6
Navsari    7    7      9     8

In [49]:
new_df.rename(index={'Gn':'Kach'},
              columns={'three':'mkc'})

         one  two  mkc  four
RAJKOT     9    8    9     7
GN         9    6    8     8
SURAT      7    7    8     5
BARDOLI    7    7    5     6
NAVSARI    7    7    9     8

# Discretizatin and Binning

In [50]:
ages=[20,22,25,27,21,23,37,31,61,45,41,32]
bins=[18,25,35,60,100]
cats=pd.cut(ages,bins)

cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [51]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [52]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [53]:
cats.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [54]:
type(cats)

pandas.Categorical

In [55]:
#  we can diretly use bins and chnage the side of interval notation :
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

## working of `.cut()`:
Find minimum
↓
Find maximum
↓
Compute range
↓
Divide range equally
↓
Assign each value to interval

In [56]:
grp_names=['Youth','YouthAdault','MiddleAged','Senior']
pd.cut(ages,bins,labels=grp_names)

['Youth', 'Youth', 'Youth', 'YouthAdault', 'Youth', ..., 'YouthAdault', 'Senior', 'MiddleAged', 'MiddleAged', 'YouthAdault']
Length: 12
Categories (4, str): ['Youth' < 'YouthAdault' < 'MiddleAged' < 'Senior']

In [57]:
data=np.random.rand(20)
print(data)

pd.cut(data,4,precision=2)
# precision for digits

[0.21054069 0.55269829 0.76329547 0.31150266 0.18739873 0.21122541
 0.07649728 0.82985395 0.47055733 0.2913541  0.74038985 0.657566
 0.44181714 0.06671824 0.32084979 0.85067076 0.71685775 0.85213706
 0.81425144 0.55812935]

[(0.066, 0.26], (0.46, 0.66], (0.66, 0.85], (0.26, 0.46], (0.066, 0.26], ..., (0.66, 0.85], (0.66, 0.85], (0.66, 0.85], (0.66, 0.85], (0.46, 0.66]]
Length: 20
Categories (4, interval[float64, right]): [(0.066, 0.26] < (0.26, 0.46] < (0.46, 0.66] < (0.66, 0.85]]

In [58]:
dn=np.random.randint(5,25,10)
dn

array([15, 13, 23, 13, 19,  6, 21,  6, 11, 11], dtype=int32)

In [59]:
print(pd.cut(dn,3,precision=1))

[(11.7, 17.3], (11.7, 17.3], (17.3, 23.0], (11.7, 17.3], (17.3, 23.0], (6.0, 11.7], (17.3, 23.0], (6.0, 11.7], (6.0, 11.7], (6.0, 11.7]]
Categories (3, interval[float64, right]): [(6.0, 11.7] < (11.7, 17.3] < (17.3, 23.0]]

## working of `.qcut()`:
Sort values
↓
Find quantiles
↓
Create boundaries
↓
Each bin gets approximately equal observations

In [60]:
sr=pd.Series([3,100,1,2])

print(pd.cut(sr,2))
print(pd.qcut(sr,2))

0    (0.901, 50.5]
1    (50.5, 100.0]
2    (0.901, 50.5]
3    (0.901, 50.5]
dtype: category
Categories (2, interval[float64, right]): [(0.901, 50.5] < (50.5, 100.0]]
0    (2.5, 100.0]
1    (2.5, 100.0]
2    (0.999, 2.5]
3    (0.999, 2.5]
dtype: category
Categories (2, interval[float64, right]): [(0.999, 2.5] < (2.5, 100.0]]

In [61]:
nsr=pd.Series([5,10,150,200,1000,2000])
print(pd.cut(nsr,3))
print(pd.qcut(nsr,3))

0      (3.005, 670.0]
1      (3.005, 670.0]
2      (3.005, 670.0]
3      (3.005, 670.0]
4     (670.0, 1335.0]
5    (1335.0, 2000.0]
dtype: category
Categories (3, interval[float64, right]): [(3.005, 670.0] < (670.0, 1335.0] < (1335.0, 2000.0]]
0      (4.999, 103.333]
1      (4.999, 103.333]
2    (103.333, 466.667]
3    (103.333, 466.667]
4     (466.667, 2000.0]
5     (466.667, 2000.0]
dtype: category
Categories (3, interval[float64, right]): [(4.999, 103.333] < (103.333, 466.667] < (466.667, 2000.0]]

In [62]:
#  we can pass our quantilers 
print(pd.qcut(nsr,[0,0.5,1]))

0     (4.999, 175.0]
1     (4.999, 175.0]
2     (4.999, 175.0]
3    (175.0, 2000.0]
4    (175.0, 2000.0]
5    (175.0, 2000.0]
dtype: category
Categories (2, interval[float64, right]): [(4.999, 175.0] < (175.0, 2000.0]]