## Add one csv file in examples folder

In [6]:
with open('examples/ex1.csv', 'w') as f:
    f.write("a,b,c,d,message\n1,2,3,4,hello\n5,6,7,8,world\n9,10,11,12,foo\n")

### Read it through read_csv function and print it

In [7]:
import pandas as pd
df=pd.read_csv("examples/ex1.csv")
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

##  Files without a header row

In [8]:
with open('examples/ex2.csv', 'w') as f:
    f.write("1,2,3,4,hello\n5,6,7,8,world\n9,10,11,12,foo\n")

In [9]:
# No header in file, auto column names 0,1,2,3,4


df2=pd.read_csv('examples/ex2.csv', header=None)
df2

# df2.columns=['one','two','three','four','five']
# print(df2)
# df2.index=['x','y','z']
# print(df2)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [10]:
df = pd.read_csv('examples/ex1.csv')
df2 = df.set_index('message')   # 'message' column becomes the index
df2

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [11]:
# no header in file, but we supply our own names

df3=pd.read_csv('examples/ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

print(df3)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

## 6.1 Reading CSV files — basics
- read_csv() = default reader, auto-detects header + types
- header=None → no header row exists, pandas auto-numbers columns
- names=[...] → explicitly supply column names

### Hierarchical index from multiple columns

In [12]:
with open('examples/csv_mindex.csv', 'w') as f:
    f.write("key1,key2,value1,value2\n")
    f.write("one,a,1,2\none,b,3,4\ntwo,c,5,6\ntwo,d,7,8\n")
    f.write("three,a,9,10\nthree,b,11,12\nfour,c,13,14\nfour,d,15,16\n")

In [13]:
parsed = pd.read_csv('examples/csv_mindex.csv', index_col=['key1', 'key2'])
print(parsed.index)
print(parsed.values)
parsed

MultiIndex([(  'one', 'a'),
            (  'one', 'b'),
            (  'two', 'c'),
            (  'two', 'd'),
            ('three', 'a'),
            ('three', 'b'),
            ( 'four', 'c'),
            ( 'four', 'd')],
           names=['key1', 'key2'])
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]

            value1  value2
key1  key2
one   a          1       2
      b          3       4
two   c          5       6
      d          7       8
three a          9      10
      b         11      12
four  c         13      14
      d         15      16

In [14]:
parsed.loc['one']
# parsed.loc[('one','a')]

      value1  value2
key2
a          1       2
b          3       4

## Passing a list to `index_col` creates a MultiIndex — a hierarchical row index with multiple levels, useful for grouped data.

### Irregular whitespace-delimited files :

In [15]:
with open('examples/ex3.txt', 'w') as f:
    f.write("            A         B         C\n")
    f.write("aaa -0.264438 -1.026059 -0.619500\n")
    f.write("bbb  0.927272  0.302904 -0.032399\n")
    f.write("ccc -0.264273 -0.386314 -0.217601\n")
    f.write("ddd -0.871858 -0.348382  1.100491\n")

In [51]:
result = pd.read_table('examples/ex3.txt', sep=r'\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

### sep=r'\s+' (regex) handles variable whitespace. If headers < data columns by exactly one,<br> pandas auto-assumes the first column is the index.

### Always use raw strings (r'\s+') for regex patterns in pandas — avoids escape sequence warnings.

## Skipping junk/comment rows — skiprows

In [17]:
with open('examples/ex4.csv', 'w') as f:
    f.write("# hey!\n")
    f.write("a,b,c,d,message\n")
    f.write("# just wanted to make things more difficult for you\n")
    f.write("# who reads CSV files with computers, anyway?\n")
    f.write("1,2,3,4,hello\n")
    f.write("5,6,7,8,world\n")
    f.write("9,10,11,12,foo\n")

In [18]:
pd.read_csv('examples/ex4.csv', skiprows=[0, 2, 3, 6])

   a  b  c  d message
0  1  2  3  4   hello
1  5  6  7  8   world

### skiprows=[list of row numbers] removes specific junk/comment rows before parsing. <br>Row numbers are 0-indexed.

###  Handling missing data on load — `na_values`

In [53]:
with open('examples/ex5.csv', 'w') as f:
    f.write("something,a,b,c,d,message\n")
    f.write("one,1,2,3,4,NA\n")
    f.write("two,5,6,,8,world\n")
    f.write("three,9,10,11,12,foo\n")

In [57]:
result = pd.read_csv('examples/ex5.csv')
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [21]:
# find the null position 
result.isnull()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [63]:
result = pd.read_csv('examples/ex5.csv', na_values=['NULL'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [64]:
# Different NA sentinels can be specified for each column in dict .

sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
result = pd.read_csv('examples/ex5.csv', na_values=sentinels)
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

### `na_values=[...]` adds custom missing-value markers globally.<br>`na_values={col: [...]}` does it per-column

##  Reading large files in pieces — nrows and chunksize

- nrows=N = preview first N rows.
- chunksize=N = process large file in N-row batches,<br> useful for memory-limited aggregation.

In [24]:
import numpy as np

rng = np.random.default_rng(0)
big_df = pd.DataFrame(
    rng.standard_normal((10000, 4)),
    columns=['one', 'two', 'three', 'four']
)
big_df['key'] = rng.choice(list('ABCDEFGHIJKLMNOPQRSTUVWXYZ'), size=10000)
big_df.to_csv('examples/ex6.csv', index=False)

In [25]:
#  nrows — just read the first N rows
r1=pd.read_csv('examples/ex6.csv', nrows=5)
r1

# Loads only the first 5 rows — fast, useful for previewing a huge file.

        one       two     three      four key
0  0.125730 -0.132105  0.640423  0.104900   M
1 -0.535669  0.361595  1.304000  0.947081   D
2 -0.703735 -1.265421 -0.623274  0.041326   N
3 -2.325031 -0.218792 -1.245911 -0.732267   H
4 -0.544259 -0.316300  0.411631  1.042513   U

In [26]:
# chunksize — read the file in pieces (for processing)

chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)
chunker

# it returns a TextFileReader object you can iterate over.
# Each iteration gives you a DataFrame of 1000 rows at a time.

## get the top 10 most frequent letters in key, computed without ever loading all 10,000 rows at once.

In [27]:

tot = pd.Series([], dtype='float64')
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)
tot[:10]

key
P    422.0
K    420.0
Q    412.0
L    410.0
H    406.0
R    405.0
C    402.0
F    401.0
A    397.0
S    396.0
dtype: float64

### Writing Data to Text Format — `to_csv`

In [28]:
# Load the missing-data file back in:
data = pd.read_csv('examples/ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [29]:
# Write it back out to a CSV:
data.to_csv('examples/out.csv')

In [30]:
with open('examples/out.csv') as f:
    print(f.read())

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [31]:
# Use a different delimiter
import sys
data.to_csv(sys.stdout, sep='|')

# NaN values show as the literal text NULL instead of blank.
data.to_csv(sys.stdout, na_rep='NULL')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo
,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [32]:
# Disable row index / column headers
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [33]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [34]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('examples/tseries.csv')
ts

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int64

## Working with Delimited Formats

In [35]:
with open('examples/ex7.csv', 'w') as f:
    f.write('"a","b","c"\n')
    f.write('"1","2","3"\n')
    f.write('"4","5","6"\n')

In [36]:
# For any file with a single-char delimeter , we can use python's built-IN CSV module 

import csv

f=open("examples/ex7.csv")
reader=csv.reader(f)

In [37]:
for line in reader:
    print(line)

# quote characters automatically stripped — not a DataFrame, just raw rows.

['a', 'b', 'c']
['1', '2', '3']
['4', '5', '6']

In [38]:
# how to use csv module perfectly

f =  open('examples/ex7.csv')
lines = list(csv.reader(f))

header, values = lines[0], lines[1:]
print(header)
print(values)

['a', 'b', 'c']
[['1', '2', '3'], ['4', '5', '6']]

In [39]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

# all column give in form of rows(dict's key :value)

{'a': ('1', '4'), 'b': ('2', '5'), 'c': ('3', '6')}

## Custom dialects for weird delimiters/quoting

In [40]:
class my_dialect(csv.Dialect):
    lineterminator="\n"
    delimiter=";"
    quotechar='"'
    quoting=csv.QUOTE_MINIMAL

with open('examples/ex7.csv','r') as g:
    reader = csv.reader(g, dialect=my_dialect)
    print(list(reader))

[['a,"b","c"'], ['1,"2","3"'], ['4,"5","6"']]

In [41]:
with open('examples/ex7.csv', 'r') as g:
    reader = csv.reader(g)   # default delimiter=',' — matches the file
    print(list(reader))

[['a', 'b', 'c'], ['1', '2', '3'], ['4', '5', '6']]

## Writing delimited files manually — csv.writer

In [42]:
with open('examples/mydata.csv', 'w') as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(('one', 'two', 'three'))
    writer.writerow(('1', '2', '3'))
    writer.writerow(('4', '5', '6'))
    writer.writerow(('7', '8', '9'))