## Binary Data Formats

'''Python DataFrame
        │
        ▼
   Binary Format
 (pickle/parquet)
        │
 Save to Disk
        │
        ▼
Binary File
        │
Later...
        │
        ▼
Read Binary File
        │
        ▼
Same DataFrame'''

### Pickle is Python's built-in module that converts any Python object into binary data so it can be stored on disk and later restored exactly as it was.

'''Python Object
      │
 Serialize
      ▼
Binary File (.pkl)
      │
 Deserialize
      ▼
Same Python Object'''

- Serialization → Object ➜ Binary file
- Deserialization → Binary file ➜ Object

In [17]:
import pandas as pd
import numpy as np
import pickle
frame=pd.read_csv("examples/ex1.csv")
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
frame.to_pickle('examples/frame_pickle')

In [10]:
pd.read_pickle('examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [18]:
df = pd.DataFrame({
    "Name":["Deep","Rahul","Aman"],
    "CGPA":[8.47,8.45,9.10]
})

with open("examples/students.pkl","wb") as f:
    pickle.dump(df,f)

In [12]:
with open("examples/students.pkl","rb") as f:
    df2 = pickle.load(f)

df2

    Name  CGPA
0   Deep  8.47
1  Rahul  8.45
2   Aman  9.10

## Using HDF5 Format

In [19]:

frame = pd.DataFrame({'a': np.random.standard_normal(100)})
store = pd.HDFStore('mydata.h5')

ImportError: `Import pytables` failed.  Use pip or conda to install the pytables package.

In [ ]:
store

In [ ]:
store['obj1'] = frame
store['obj1_col'] = frame['a']
store['obj1']

In [ ]:
store.put("obj2", frame, format="table")
store.select('obj2',where=['index>=10 and index<=15'])

In [ ]:
store.close()

In [ ]:
frame.to_hdf('mydata.h5',key='obj',format='table')

In [ ]:
pd.read_hdf('mydata.h5',key='obj',where=['index < 5'])

##  Reading MS Excel Files

In [ ]:
xlsx = pd.ExcelFile('examples/ex_excel.xlsx')
xlsx.sheet_names

In [ ]:
pd.read_excel(xlsx,'Sheet1')
# we can also pass file name instead of xlsx

## Interacting with WebAPIs

Web API
   │
HTTP GET request
   │
JSON response
   │
Python (requests)
   │
Pandas DataFrame

In [ ]:
import requests
url='https://api.github.com/repos/pandas-dev/pandas/issues'
resp=requests.get(url)
resp

In [ ]:
data=resp.json()
data[0]['title']

'BUG: omit hidden cells from Styler.to_typst'

In [16]:
issues=pd.DataFrame(data,columns=['number','title','labels','state'])
issues

NameError: name 'data' is not defined

In [15]:
import requests

import pandas as pd

url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

data = response.json()

info = pd.DataFrame(data)

info.head()

ConnectionError: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /users (Caused by NameResolutionError("HTTPSConnection(host='jsonplaceholder.typicode.com', port=443): Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))

In [14]:
info=pd.DataFrame(data)
info.iloc[0:5,]

NameError: name 'data' is not defined

In [ ]:
address_df = pd.json_normalize(info["address"])

address_df.head()

## Interacing with Databases

In [ ]:
# Create database

import sqlite3

query="""
CREATE TABLE test
(
 a VARCHAR(20),
 b VARCHAR(20),
 c REAL,
 d INTEGER
);"""

con=sqlite3.connect('mydata.sqlite')
con.execute(query)

In [ ]:
data = [('jecob','US',1.25,6),
        ('yosho','korea',3.2,4),
        ('steve','sydney',1.4,5)]

stmt="INSERT INTO test VALUES(?,?,?,?)"
con.executemany(stmt,data)

In [ ]:
con.commit()

In [ ]:
cursor=con.execute('select * from test')
rows=cursor.fetchall()
rows

In [ ]:
cursor.description

In [ ]:
con.close()

In [ ]:
import pandas as pd
ddf=pd.DataFrame(rows,columns=[x[0] for x in cursor.description])
ddf

NameError: name 'rows' is not defined

## Pandas provides one function that does all of this internally.

In [ ]:
con = sqlite3.connect("mydata.sqlite")

df = pd.read_sql_query("SELECT * FROM test", con)

df

In [ ]:
import sys
print(sys.executable)

In [ ]:
import sqlalchemy as sqla
db=sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select * from test',db)