## Summarizing and Computing Descriptive Statistcs

# Statistical Moments

A **statistical moment** is a mathematical measure that describes a specific property of a dataset or probability distribution.

Each higher-order moment provides additional information about the distribution.

| Moment | Power | Measures | Statistical Measure | What it tells |
|:------:|:-----:|----------|---------------------|---------------|
| **1st Moment** | 1 | Center | Mean (μ) | Where the data is centered (average value). |
| **2nd Moment** | 2 | Spread | Variance (σ²) / Standard Deviation (σ) | How spread out the data is around the mean. |
| **3rd Moment** | 3 | Asymmetry | Skewness | Whether the distribution is tilted to the left or right. |
| **4th Moment** | 4 | Tail Heaviness | Kurtosis | How heavy or light the tails are (tendency to produce extreme values). |

In [1]:
# Pandas 3.x Update

# • Series.argmax() ❌ Removed
# • Series.argmin() ❌ Removed
# • DataFrame.argmax() ❌ Removed
# • DataFrame.argmin() ❌ Removed

# Use:

# ✔ idxmax() → returns index label
# ✔ idxmin() → returns index label

# If you need integer positions:

# ✔ series.to_numpy().argmax()
# ✔ series.to_numpy().argmin()
# ✔ df.to_numpy().argmax()
# ✔ df.to_numpy().argmin()

In [2]:
import numpy as np
import pandas as pd
df=pd.DataFrame([
    [1.4,np.nan,5.6],
    [7.1,-4.5,np.nan],
    [np.nan,np.nan,8],
    [0.75,-1.3,0.9]]

    ,index=list('abcd')
    ,columns=['one','two','three']
)
df

    one  two  three
a  1.40  NaN    5.6
b  7.10 -4.5    NaN
c   NaN  NaN    8.0
d  0.75 -1.3    0.9

In [3]:
# By default column wise 
print(df.sum())
print(df.sum(axis='columns'))     #or df.sum(axis=1)

#  By default, sum() ignores NaN, so it behaves as if NaN were 0.
# By Default (skipna=True)
# But technically pandas is not replacing NaN with 0. It is skipping (ignoring) the NaN value.
# if we pass skipna=False sum becomes NAN.
print(df.sum(skipna=False))

one       9.25
two      -5.80
three    14.50
dtype: float64
a    7.00
b    2.60
c    8.00
d    0.35
dtype: float64
one     NaN
two     NaN
three   NaN
dtype: float64

In [4]:
# These methods , like idxmin() and idxmax() return indirect statistics
#  like the index value where the minimum or maximum values are attained 

print(df.idxmax())         # max's_index and min's_ndex 
print(df.idxmin())

# removed from 3.03
# print(df.argmax())          
# print(df.argmin())

one      b
two      d
three    c
dtype: str
one      d
two      b
three    d
dtype: str

In [5]:
# numpy function : --> cumsum()
print(df.cumsum())

    one  two  three
a  1.40  NaN    5.6
b  8.50 -4.5    NaN
c   NaN  NaN   13.6
d  9.25 -5.8   14.5

In [6]:
#  Give statistical analysis .
df.describe()

            one       two     three
count  3.000000  2.000000  3.000000
mean   3.083333 -2.900000  4.833333
std    3.493685  2.262742  3.611556
min    0.750000 -4.500000  0.900000
25%    1.075000 -3.700000  3.250000
50%    1.400000 -2.900000  5.600000
75%    4.250000 -2.100000  6.800000
max    7.100000 -1.300000  8.000000

In [7]:
obj=pd.Series(['a','a','b','c'] * 4) 
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [8]:
df

    one  two  three
a  1.40  NaN    5.6
b  7.10 -4.5    NaN
c   NaN  NaN    8.0
d  0.75 -1.3    0.9

In [9]:

print(df.quantile(0.5))

one      1.4
two     -2.9
three    5.6
Name: 0.5, dtype: float64

In [10]:
#  find the count of non-NAN
print(df)

print(df.count(),      '\n\n')

print("max: \n",df.max())
print("min: \n",df.min())

    one  two  three
a  1.40  NaN    5.6
b  7.10 -4.5    NaN
c   NaN  NaN    8.0
d  0.75 -1.3    0.9
one      3
two      2
three    3
dtype: int64


max:
 one      7.1
two     -1.3
three    8.0
dtype: float64
min:
 one      0.75
two     -4.50
three    0.90
dtype: float64

In [11]:
import pandas as pd
import numpy as np

d2 = pd.DataFrame({
    "Math":    [90, 80, 90, 70, np.nan],
    "Science": [85, 95, 85, 75, 90],
    "English": [88, 82, 91, 88, 85]
    
})

d2

   Math  Science  English
0  90.0       85       88
1  80.0       95       82
2  90.0       85       91
3  70.0       75       88
4   NaN       90       85

### sum()

imp arguments:
- axis=0      # column-wise (default)
- axis=1      # row-wise
- skipna=True # ignore NaN (default)
- skipna=False
- numeric_only=True

In [12]:
print(d2.sum())
# Row sum : 
print(d2.sum(axis=1))

Math       330.0
Science    430.0
English    434.0
dtype: float64
0    263.0
1    257.0
2    266.0
3    233.0
4    175.0
dtype: float64

In [13]:
# mean()
print(d2.mean())
print(d2.mean(axis=1))

Math       82.5
Science    86.0
English    86.8
dtype: float64
0    87.666667
1    85.666667
2    88.666667
3    77.666667
4    87.500000
dtype: float64

In [14]:
# median()
print(d2.median())
print(d2.median(axis=1))

Math       85.0
Science    85.0
English    88.0
dtype: float64
0    88.0
1    82.0
2    90.0
3    75.0
4    87.5
dtype: float64

In [15]:
# min() and max()

print(d2.min())
print(d2.min(axis=1)    ,"\n\n")

print(d2.max())
print(d2.max(axis=1))

Math       70.0
Science    75.0
English    82.0
dtype: float64
0    85.0
1    80.0
2    85.0
3    70.0
4    85.0
dtype: float64


Math       90.0
Science    95.0
English    91.0
dtype: float64
0    90.0
1    95.0
2    91.0
3    88.0
4    90.0
dtype: float64

In [16]:
# prod()
d2.prod(axis=1)

0    673200.0
1    623200.0
2    696150.0
3    462000.0
4      7650.0
dtype: float64

In [17]:
# var()
# Variance.
print(d2.var()      ,"\n")
print(d2.var(axis=1)    ,"\n")


print(d2.var(ddof=0))

Math       91.666667
Science    55.000000
English    11.700000
dtype: float64

0     6.333333
1    66.333333
2    10.333333
3    86.333333
4    12.500000
dtype: float64

Math       68.75
Science    44.00
English     9.36
dtype: float64

### What is ddof?

- **ddof** stands for `*Delta Degrees of Freedom*`  
- It tells pandas what number to subtract from **N** in the denominator  
- Used in variance and standard deviation calculations  
- Formula becomes:


$$
\text{Variance} = \frac{\text{Sum of squared deviations}}{N - ddof}
$$



👉 Common case: `ddof=1` → denominator becomes \(N-1\) (sample variance)

In [18]:
# std()
# Standard deviation.


d2.std()

Math       9.574271
Science    7.416198
English    3.420526
dtype: float64

### skew()

**Purpose:**  
Measures the asymmetry (lack of symmetry) of a distribution.  
It tells you which side has the longer tail.

- skew = 0 → Symmetric  
- skew > 0 → Right-skewed (tail on the right)  
- skew < 0 → Left-skewed (tail on the left)
- Skewness measures how asymmetric (uneven) a distribution is.

## case 1
*value=0*

- You can say:

Distribution is approximately symmetric.
Left and right sides are almost balanced.<br>
`Mean ≈ Median ≈ Mode.`

### Case 2
*2.3 > 0*

- You can say:

Data is positively (right) skewed.
There are some unusually large values (high outliers).<br>
`Mean > Median.`
Long tail on the right.

- example: salary <br>
20k<br>
22k<br>
23k<br>
24k<br>
25k<br>
30k<br>
5 crore

### Case 3
*-1.7 < 0*

- You can say:

Data is negatively (left) skewed.
There are some unusually small values.
Mean < Median.
Long tail on the left.

-Example : <br>

5<br>
40<br>
42<br>
43<br>
44<br>
45<br>
46<br>

In [19]:
s = pd.Series([2, 4, 6, 8, 50])
print(s.skew())

# Returns => Positive value
# Meaning => Right-skewed

2.168186919474709

In [20]:
s = pd.Series([1, 40, 42, 44, 46])
print(s.skew())

# Returns => Negative value
# Meaning => Left-skewed

-2.158332566421802

### Skewness Interpretation

| Skewness Value | Interpretation |
|---|---|
| **-0.5 to +0.5** | Approximately **symmetric** |
| **-1 to -0.5** | **Moderately negatively skewed** |
| **+0.5 to +1** | **Moderately positively skewed** |
| **< -1** | **Highly negatively skewed** |
| **> +1** | **Highly positively skewed** |

### ML / EDA Usage of skew()

- Very useful before training models  
- Large skewness → feature not normally distributed  
- Transformations to reduce skewness:
  - `np.log()`  
  - `np.sqrt()`  
  - **Box-Cox**  
  - **Yeo-Johnson**

 Skewness (3rd Standardized Moment)

### Formula

 Skewness Formula

$$
\boxed{
\text{Skewness}
=
\frac{\frac{1}{n}\sum_{i=1}^{n}(x_i-\mu)^3}{\sigma^3}
}
$$

### Where

- $n$ = Number of observations
- $x_i$ = Each data value
- $\mu$ = Mean
- $\sigma$ = Standard deviation
### Interpretation

- **Skewness = 0** → Symmetric distribution
- **Skewness > 0** → Right (Positive) skew
- **Skewness < 0** → Left (Negative) skew

$$
\boxed{
\text{Kurtosis}
=
\frac{\frac{1}{n}\sum_{i=1}^{n}(x_i-\mu)^4}{\sigma^4}
}
$$

### kurt()

**Purpose:**  
Measures how heavy (or light) the tails of a distribution are compared to a normal distribution.  
kurtosis measures how heavy the tails are, which tells us how many extreme values (outliers) are present.
- **Tails** = values far away from the center (extreme values).  
- Most data usually lies near the middle, but tails show how far extreme values stretch.


---
#### Visual intuition
<!-- 
           Center
              ▲
              │
        ***********
      ***         ***
    **               **
---*-------------------*---
  Left Tail         Right Tail
-->

---
#### Heavy tails
- Example: Marks → `5, 10, 48, 49, 50, 51, 52, 95, 100`  
- Most students are near 50, but **5, 10, 95, 100** are far away.  
- Graph stretches farther → **heavy tails**.  
- Called "heavy" because **more data lives in the tails** (more extreme values than expected).

---
#### Visual intuition

<!-- 
*                     *
 \                   /
  \                 /
      ***********
    ***         ***
-------------------------

 -->
--- 

The graph stretches farther.

These stretched ends are called

Heavy tails.

#### Light tails
- Example: Marks → `48, 49, 49, 50, 50, 50, 51, 51, 52`  
- Nobody is far away, everything hugs the center.  
- Graph has **tiny tails** → **light tails**.

---
#### Visual intuition
<!-- 
        **************
      ******************
------------------------- 
-->
---

#### What does `kurt()` tell us?
It answers: **"How many extreme values (outliers) does this data have?"**

- **High kurtosis** → more extreme values, heavy tails  
  Example: `1, 2, 3, 4, 5, 6, 100` → one huge outlier → high kurtosis  
- **Low kurtosis** → fewer extreme values, light tails  
  Example: `48, 49, 50, 50, 51, 52` → everything close → low kurtosis  
- **Normal kurtosis (~0)** → distribution similar to normal curve

---

👉 In **EDA/ML**, kurtosis helps detect **outliers** and understand tail behavior of features before training models.

In [21]:
# Measures how heavy the tails of the distribution are.

s1=pd.Series([5, 10, 48, 49, 50, 51, 52, 95, 100])
print(s1.kurt())
s2=pd.Series([48, 49, 49, 50, 50, 50, 51, 51, 52])
print(s2.kurt())

s3=pd.Series ([ -100 ,48, 49, 50, 50, 51, 52, 300])
print(s3.kurt())

-0.23421717841204703
-0.2857142857142856
4.388982575574092

kurt() < 0 :
Less outliers
Light tails

kurt() = 0 :
Normal outliers
Normal tails

kurt() > 0 :
More outliers
Heavy tails

| Kurtosis Value | Interpretation                                              |
| -------------- | ----------------------------------------------------------- |
| **≈ 0**        | **Mesokurtic** — similar to normal distribution             |
| **> 0**        | **Leptokurtic** — heavier tails / more extreme values       |
| **< 0**        | **Platykurtic** — lighter tails / fewer extreme values      |

### .cummax()  
**Purpose:**  
Returns the maximum value up to each row (cumulative maximum).  
It keeps track of the largest value encountered so far, row by row.  

### .cummin()  
**Purpose:**  
Returns the minimum value up to each row (cumulative minimum).  
It keeps track of the smallest value encountered so far, row by row.

In [22]:
# Running maximum.
# Running minmum.

print(d2)
print(d2.cummax())
print(d2.cummin())

   Math  Science  English
0  90.0       85       88
1  80.0       95       82
2  90.0       85       91
3  70.0       75       88
4   NaN       90       85
   Math  Science  English
0  90.0       85       88
1  90.0       95       88
2  90.0       95       91
3  90.0       95       91
4   NaN       95       91
   Math  Science  English
0  90.0       85       88
1  80.0       85       82
2  80.0       85       82
3  70.0       75       82
4   NaN       75       82

### .diff()

**Purpose:**  
Returns the difference between the current element and the previous element.  
It shows how much change happened row by row.

- Positive value → increase compared to previous row  
- Negative value → decrease compared to previous row

In [23]:
print(d2.diff())

#    Math  Science  English
# 0   NaN     NaN     NaN   # first row has no previous
# 1 -10.0    10.0    -6.0   # 80-90, 95-85, 82-88
# 2  10.0   -10.0     9.0   # 90-80, 85-95, 91-82
# 3 -20.0   -10.0    -3.0   # 70-90, 75-85, 88-91
# 4   NaN    15.0    -3.0   # NaN-70, 90-75, 85-88

print(d2["Math"].diff())


# .diff(period=1) → current row minus previous row

# .diff(period=2) → current row minus 2 rows before

# .diff(period=n) → current row minus n rows befor

   Math  Science  English
0   NaN      NaN      NaN
1 -10.0     10.0     -6.0
2  10.0    -10.0      9.0
3 -20.0    -10.0     -3.0
4   NaN     15.0     -3.0
0     NaN
1   -10.0
2    10.0
3   -20.0
4     NaN
Name: Math, dtype: float64

In [24]:
newsr=pd.Series([80,80,80,90,80,80,70,70])
newsr.diff()

0     NaN
1     0.0
2     0.0
3    10.0
4   -10.0
5     0.0
6   -10.0
7     0.0
dtype: float64

In [25]:
pd.Series([10,20,20,30,40]).pct_change()

0         NaN
1    1.000000
2    0.000000
3    0.500000
4    0.333333
dtype: float64

In [26]:
# pct_change()
# Percentage change.
# formula : 
# (Current-Previous)/Previous

d2["Science"].pct_change()

0         NaN
1    0.117647
2   -0.105263
3   -0.117647
4    0.200000
Name: Science, dtype: float64

# Rule to remember:

- diff() → Absolute change<br>
- pct_change() → Relative (fractional) change (multiply by 100 if you want a percentage)