In [13]:
# Integer_Indexes
import numpy as np
import pandas as pd
s1=pd.Series(np.arange(6.))
# print(s1)
# s1[-1]
# s1.loc[-1]
print(s1.iloc[-1])
# Throws an ValueError
# coz it is ambigous

5.0

In [14]:
s2=pd.Series(np.arange(4),index=['a','b','c','d'])
print(s2[:1])
# print(s2.loc[:1])      throws error
print(s2.iloc[:1])
print(s2.iloc[-1])

a    0
dtype: int64
a    0
dtype: int64
3

In [15]:
#  Arithmetic & Data Alignment
s1 = pd.Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1], index=['a','c','e','f','g'])
print(s1 + s2)

# union of row and column labels; mismatches → NaN 
# Same with DF

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [16]:
df1 = pd.DataFrame({
    "A":[1,2],
    "B":[3,4]
})

df2 = pd.DataFrame({
    "A":[10,20],
    "C":[30,40]
})

print(df1+df2)

    A   B   C
0  11 NaN NaN
1  22 NaN NaN

In [17]:
# use fill_value
sum=df1.add(df2,fill_value=0)
sum

#  if we pass fill_value=0 then it will be add all columns
#  with their value if same row column are exist then add .

# Important Note 
# fill_value=0 does not modify df1 or df2.
# It is used only during that arithmetic operation.
# Original DataFrames remain unchanged.

    A    B     C
0  11  3.0  30.0
1  22  4.0  40.0

In [18]:
print(df1 - df2     ,"\n")
df1.sub(df2,fill_value=0)

    A   B   C
0  -9 NaN NaN
1 -18 NaN NaN

    A    B     C
0  -9  3.0 -30.0
1 -18  4.0 -40.0

In [19]:
df1.mul(df2,fill_value=0)        # df1 *df2

# here fill value = 0 coz 0 is used inplace of NaN .

    A    B    C
0  10  0.0  0.0
1  40  0.0  0.0

### What is radd, rsub, rdiv?

- The r stands for "reverse" (or reflected).

In [20]:
print(df1.radd(5))    #  5  + df1 

print(df2.rsub(2))    #  2  - df2

print(df2.div(5))     #  df1 / 5

print(df2.rdiv(5))    #  5   / df2

# other methods : 
# floordiv, rfloordiv  -->  //
# mul, rmul --> *
# pow, rpow  --> **

   A  B
0  6  8
1  7  9
    A   C
0  -8 -28
1 -18 -38
     A    C
0  2.0  6.0
1  4.0  8.0
      A         C
0  0.50  0.166667
1  0.25  0.125000

In [21]:
# Reindex with fill_value
df1.reindex(columns=["A","B","C","D"], fill_value=0)

# Here, newly created columns (C and D) are filled with 0 instead of NaN.

   A  B  C  D
0  1  3  0  0
1  2  4  0  0

In [22]:
# DataFrame ↔ Series Arithmetic (Broadcasting)

df = pd.DataFrame({
    "A": [1, 2],
    "B": [3, 4]
})

s = pd.Series({"A": 10, "B": 20})

df + s

# This is called broadcasting because the one-dimensional Series is
# automatically expanded across the DataFrame without you having to write a loop.
# To broadcast across columns (match on rows) instead, use axis='index':

    A   B
0  11  23
1  12  24

In [23]:
D=pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('xyz'))
print(D)
p=pd.Series(np.arange(3),index=['x','y','z'])

print(D-p)

   x   y   z
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11
   x  y  z
0  0  0  0
1  3  3  3
2  6  6  6
3  9  9  9

In [24]:
h=pd.Series(D["y"])
D.sub(h,axis="index")

   x  y  z
0 -1  0  1
1 -1  0  1
2 -1  0  1
3 -1  0  1