- DataFrame → Mutable ✅
- Series → Mutable ✅
- Their Index (row labels and column labels) → Immutable ✅

In [1]:
import numpy as np
import pandas as pd
s = pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

*A Pandas Series has no column labels because it is one-dimensional.*

In [2]:
s.index         # how to get seperately 
s.values

array([10, 20, 30, 40])

In [3]:
# if we use numpy functions or operation such as boolean indexing , will preserve the index-values 
# s*5
s [s > 10]

1    20
2    30
3    40
dtype: int64

In [4]:

# Custom index
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s['b'])   # 20

print(type(s))

20
<class 'pandas.Series'>

In [5]:
# we can also check indices are available or not ?
# 'a' in s
'e' in s

False

In [6]:
#  The 'isnull' and not 'notnull' functions in pandas should be used to detect missing data

# --> there are two way to use this
# 1) pd.isnull(obj)   also work for list , tupple
# 2) obj.isnull()      only for for pandas ds

md=pd.DataFrame({
    "Rajkot": [4500] ,
    "Ahmedabad":[5600] ,
    "Gandhinagar":[np.nan] ,
    "Bhavnagar":[5900]
})

# md.notnull()          # return false for NaN 
# md.isnull()           # return true for NaN
pd.isnull(md)

   Rajkot  Ahmedabad  Gandhinagar  Bhavnagar
0   False      False         True      False

**A useful Series feature for many applications is that it automatically aligns by index label in arithmatic operations**

In [7]:
obj1 = {
    "Rajkot": 4500,
    "Ahmedabad": 5600,
    "Gandhinagar": 5000,
    "Bhavnagar": 5900
}

obj2 = {
    "Surat": 3400,
    "Rajkot": 4500,
    "Ahmedabad": 5600,
    "Gandhinagar": np.nan,
    "Bhavnagar": 5900
}

OBJ1 = pd.Series(obj1)
OBJ2 = pd.Series(obj2)
Z=OBJ1+OBJ2
Z.isnull()
Z.notnull()

Ahmedabad       True
Bhavnagar       True
Gandhinagar    False
Rajkot          True
Surat          False
dtype: bool

In [8]:


data={
    "name":["Kohli","Williamson","Root","Smith"],

    "Centuries":[85,48,61,49],
    "Nation":["IND","NZ","ENG","AUS"]
}
# converted into DataFrame 
df=pd.DataFrame(data)
print(df)
print(type(df))
print("\n")

# Series with different indices 
a=pd.Series([3,5,2,6,7],index=["a","b","c","d","e"])
print(a,"\n")

print(a.dtype ,"\n",df.dtypes)

         name  Centuries Nation
0       Kohli         85    IND
1  Williamson         48     NZ
2        Root         61    ENG
3       Smith         49    AUS
<class 'pandas.DataFrame'>


a    3
b    5
c    2
d    6
e    7
dtype: int64

int64
 name           str
Centuries    int64
Nation         str
dtype: object

In [9]:
df=pd.DataFrame({
    "name":["jeck","tonny","joseph"],
    "Sim":["jio","vi","airtle"],
    "nation":["aus","nz","eng"],
    "salary":[50000,45000,340000]

})

print(df,"\n")
print("Shape : ",df.shape,"\n")        # (rows, columns)
print(df.dtypes,"\n")       # data type of each column
print(df.head(1),"\n")      # first 2 rows
print(df.tail(2))      # last 2 rows
# df.info()       # summary — nulls, dtypes, memory
# df.describe()   # stats — mean, std, min, max

     name     Sim nation  salary
0    jeck     jio    aus   50000
1   tonny      vi     nz   45000
2  joseph  airtle    eng  340000

Shape :  (3, 4)

name        str
Sim         str
nation      str
salary    int64
dtype: object

   name  Sim nation  salary
0  jeck  jio    aus   50000

     name     Sim nation  salary
1   tonny      vi     nz   45000
2  joseph  airtle    eng  340000

In [ ]:

df1=pd.read_csv("sample.csv")


print(df1)
print('\n')
df1.head(2)      # head and tail give by default 5 samples upper and lower

   Student_id     Name  Age  Marks
0         101     Alex   19   85.5
1         102   Joseph   20   91.0
2         103    Krish   18   76.5
3         104    Rohan   21   88.0
4         105      Ved   20   95.5
5         106    Tejas   19   79.0
6         107  Darshan   22   83.5
7         108     Goku   21   90.0

   Student_id    Name  Age  Marks
0         101    Alex   19   85.5
1         102  Joseph   20   91.0

In [11]:
df1.tail(2)

   Student_id     Name  Age  Marks
6         107  Darshan   22   83.5
7         108     Goku   21   90.0

In [12]:
# Give random rows (by default 1) : 
df1.sample()

   Student_id  Name  Age  Marks
0         101  Alex   19   85.5

In [13]:
print("df1 info : ")
df1.info()        # .info() gives complete information about DataFrame

df1 info :
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_id  8 non-null      int64
 1   Name        8 non-null      str
 2   Age         8 non-null      int64
 3   Marks       8 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 388.0 bytes

In [14]:
print(df1.index,"\n")         # .index displays row index !!
print("Data types : \n")
print(df1.dtypes)        #  shows data types of every columns

RangeIndex(start=0, stop=8, step=1)

Data types :

Student_id      int64
Name              str
Age             int64
Marks         float64
dtype: object

In [15]:
df1.columns

Index(['Student_id', 'Name', 'Age', 'Marks'], dtype='str')

In [16]:
# Shows statistical summary of numerical columns 
df1.describe()

       Student_id        Age     Marks
count     8.00000   8.000000   8.00000
mean    104.50000  20.000000  86.12500
std       2.44949   1.309307   6.33443
min     101.00000  18.000000  76.50000
25%     102.75000  19.000000  82.37500
50%     104.50000  20.000000  86.75000
75%     106.25000  21.000000  90.25000
max     108.00000  22.000000  95.50000

**Creating DataFrame from Dictionary , List and np_array**

In [17]:
d1={
    "host":['F','A','A','N','G'],
    "no":[3,4,2,4,1]
}
d11=pd.DataFrame(d1)
d11

  host  no
0    F   3
1    A   4
2    A   2
3    N   4
4    G   1

In [18]:
d2=[
    ["new","jeck",55],
    ["old","ajju",84]
]
d22=pd.DataFrame(d2,columns=["cat.","name","level"])
d22

  cat.  name  level
0  new  jeck     55
1  old  ajju     84

In [19]:
import numpy as np

data = np.array([
    [101, "Alex", 85.5],
    [102, "Joseph", 91.0],
    [103, "Krish", 76.5]
])

df_np = pd.DataFrame(data, columns=["Student_ID", "Name", "Marks"])
df_np

  Student_ID    Name Marks
0        101    Alex  85.5
1        102  Joseph  91.0
2        103   Krish  76.5

## Why we save DataFrames to CSV
-  To store data permanently outside Python.
-  To share datasets with others (Excel, Google Sheets, etc. can open CSV easily).

-  To reuse later without retyping or regenerating data.

-  To export results after cleaning, filtering, or analysis.

In [20]:


# Example DataFrame
data = {
    "Student_ID": [101, 102, 103],
    "Name": ["grey","hugh","darvin"],
    "Marks": [33,55,66]
}
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("students.csv", index=False)
pd.read_csv("students.csv")                     # Quick check after saving

   Student_ID    Name  Marks
0         101    grey     33
1         102    hugh     55
2         103  darvin     66

#### Both the Series object itself and its index have **name** attribbute ,<br> which integrates with other key areas of pandas functionality

In [21]:
z=["c1","c2","c3","c4","c5"]
d=pd.Series([4,5,2,6,2],index=z)

 
d.name="new"
d.index.name="sr"

df5=d.to_frame()
df5

    new
sr
c1    4
c2    5
c3    2
c4    6
c5    2